/**
 * AgriWaste Marketplace — Comprehensive Production Dataset
 * Contains 50+ Listings, 20+ Farmers, 15+ Buyers, 30+ Orders, 30+ Reviews,
 * Predefined Categories with Waste-to-Product Mappings, and Sustainability Metrics.
 */

// ==========================================
// 1. CATEGORIES & WASTE-TO-PRODUCT MAPPINGS
// ==========================================
export const INITIAL_CATEGORIES = [
  {
    id: "paddy-straw",
    name: "Paddy / Rice Straw",
    group: "Crop Residues",
    count: "14,250 Tons",
    listingsCount: 42,
    icon: "sprout",
    description: "Ideal for cattle fodder, bio-pellets, mushroom beds, eco-tableware, and compost mulch.",
    image: "/images/waste/paddy-straw.jpg",
    applications: [
      { name: "Animal Fodder & Silage", industry: "Dairy & Livestock", demand: "High", valueAdd: "Medium" },
      { name: "Biomass Briquettes & Pellets", industry: "Renewable Energy", demand: "Very High", valueAdd: "High" },
      { name: "Mushroom Cultivation Bedding", industry: "Horticulture", demand: "High", valueAdd: "High" },
      { name: "Biochar & Soil Conditioner", industry: "Organic Farming", demand: "Medium", valueAdd: "High" },
      { name: "Pulp & Tree-Free Paper", industry: "Paper Mills", demand: "High", valueAdd: "Very High" }
    ],
    storageGuidelines: "Store in elevated dry sheds covered with UV-resistant tarpaulin. Ensure moisture < 14% to prevent spontaneous heating.",
    transportGuidelines: "Transport in machine-compressed square/round bales on flatbed trucks with tie-down straps."
  },
  {
    id: "wheat-straw",
    name: "Wheat Straw",
    group: "Crop Residues",
    count: "9,800 Tons",
    listingsCount: 35,
    icon: "wheat",
    description: "Premium dry golden straw for dairy animal feed, paper pulp, and particle boards.",
    image: "/images/waste/wheat-straw.jpg",
    applications: [
      { name: "High-Digestibility Cattle Feed", industry: "Animal Husbandry", demand: "Very High", valueAdd: "High" },
      { name: "Eco-Packaging & Molded Pulp", industry: "Sustainable Packaging", demand: "High", valueAdd: "Very High" },
      { name: "Cellulosic Bio-Ethanol", industry: "Biofuel Refineries", demand: "Medium", valueAdd: "High" },
      { name: "Straw Acoustic Panels", industry: "Construction & Insulation", demand: "Medium", valueAdd: "High" }
    ],
    storageGuidelines: "Store in well-ventilated dry warehouses protected from rodents and rainwater leaks.",
    transportGuidelines: "Standard 30kg high-density bales loaded on 10-wheel tippers or trucks."
  },
  {
    id: "sugarcane-bagasse",
    name: "Sugarcane Bagasse",
    group: "Crop Residues",
    count: "18,400 Tons",
    listingsCount: 48,
    icon: "trees",
    description: "High-calorific fibrous biomass for industrial boilers, compostable tableware, and bio-energy.",
    image: "/images/waste/sugarcane-bagasse.jpg",
    applications: [
      { name: "Boiler Cogeneration Fuel", industry: "Sugar & Power Plants", demand: "Very High", valueAdd: "Medium" },
      { name: "Biodegradable Tableware", industry: "Eco-Plastics Alternative", demand: "Very High", valueAdd: "Very High" },
      { name: "Kraft Paper & Corrugated Box", industry: "Packaging Industry", demand: "High", valueAdd: "High" },
      { name: "Enzymatic Sugars / Bio-CNG", industry: "Clean Energy", demand: "High", valueAdd: "High" }
    ],
    storageGuidelines: "Store in dedicated yard bunkers. Maintain sprinkler cooling for large bulk piles to regulate internal fermentation heat.",
    transportGuidelines: "Bulk open-top high-sided tipper trucks with tarpaulin netting."
  },
  {
    id: "cotton-stalk",
    name: "Cotton Stalks & Waste",
    group: "Crop Residues",
    count: "6,200 Tons",
    listingsCount: 26,
    icon: "flower-2",
    description: "Woody high-lignin stems for compressed fuel logs, particle board, and mushroom substrate.",
    image: "/images/waste/cotton-stalk.jpg",
    applications: [
      { name: "Industrial Fireplace Logs & Pellets", industry: "Biofuel", demand: "High", valueAdd: "High" },
      { name: "Medium Density Particle Board", industry: "Furniture & Building", demand: "High", valueAdd: "Very High" },
      { name: "Activated Carbon Precursor", industry: "Chemical Processing", demand: "Medium", valueAdd: "High" }
    ],
    storageGuidelines: "Dry outdoor stacking with plastic covers; prevent ground water absorption.",
    transportGuidelines: "Chipped or chopped form in tippers or bundled stems on flatbed trailers."
  },
  {
    id: "groundnut-shell",
    name: "Groundnut Shells / Husks",
    group: "Crop Residues",
    count: "4,650 Tons",
    listingsCount: 22,
    icon: "nut",
    description: "Dense shells used for white-coal briquettes, furfural extraction, and particle boards.",
    image: "/images/waste/groundnut-shell.jpg",
    applications: [
      { name: "High-Calorie Bio-Coal Briquettes", industry: "Boiler Fuel", demand: "Very High", valueAdd: "High" },
      { name: "Furfural & Chemical Solvents", industry: "Bio-Chemicals", demand: "Medium", valueAdd: "Very High" },
      { name: "Poultry Litter Bedding", industry: "Poultry Farming", demand: "High", valueAdd: "Medium" }
    ],
    storageGuidelines: "Store in closed silo sheds. Keep dry to prevent fungal growth.",
    transportGuidelines: "50kg gunny bags or bulk container trucks."
  },
  {
    id: "coconut-husk-shell",
    name: "Coconut Husk & Shells",
    group: "Crop Residues",
    count: "8,950 Tons",
    listingsCount: 39,
    icon: "circle-dot",
    description: "Coir pith, husk fiber, and dense shells for activated carbon, hydroponics, and geotextiles.",
    image: "/images/waste/coconut-husk-shell.jpg",
    applications: [
      { name: "Activated Carbon Filtration", industry: "Water & Air Purification", demand: "Very High", valueAdd: "Very High" },
      { name: "Coir Pith Hydroponic Grow Substrate", industry: "Horticulture & Export", demand: "Very High", valueAdd: "High" },
      { name: "Erosion Control Geotextiles", industry: "Infrastructure & Civil", demand: "High", valueAdd: "High" },
      { name: "Hookah Charcoal & BBQ Briquettes", industry: "Consumer Goods", demand: "High", valueAdd: "High" }
    ],
    storageGuidelines: "Open yard storage for shells; covered dry area for coir pith blocks.",
    transportGuidelines: "Compressed 5kg coir blocks in pallets or loose shells in open-body trucks."
  },
  {
    id: "banana-waste",
    name: "Banana Pseudo-Stem & Leaves",
    group: "Crop Residues",
    count: "3,400 Tons",
    listingsCount: 19,
    icon: "leaf",
    description: "Fiber extraction for eco-textiles, organic sap liquid fertilizer, and handmade paper.",
    image: "/images/waste/banana-waste.jpg",
    applications: [
      { name: "Eco-Textile Yarn & Sanitary Pads", industry: "Textile & Hygiene", demand: "High", valueAdd: "Very High" },
      { name: "Liquid Organic Growth Promoter (Sap)", industry: "Organic Fertilizer", demand: "High", valueAdd: "High" },
      { name: "Handmade Artisanal Paper", industry: "Crafts & Packaging", demand: "Medium", valueAdd: "High" }
    ],
    storageGuidelines: "Process within 48 hours of harvest or shade-dry to prevent natural decomposition.",
    transportGuidelines: "Immediate truck transport from farm gates to decortication units."
  },
  {
    id: "maize-stalk-cob",
    name: "Maize Stalks & Cobs",
    group: "Crop Residues",
    count: "5,100 Tons",
    listingsCount: 25,
    icon: "sun",
    description: "Corn stalks, leaves, and cobs for animal silage, biochar, and cellulosic ethanol.",
    image: "/images/waste/maize-stalk-cob.jpg",
    applications: [
      { name: "Cattle Silage & Total Mixed Ration", industry: "Dairy & Livestock", demand: "High", valueAdd: "Medium" },
      { name: "Abrasive Grit & Industrial Absorbent", industry: "Manufacturing", demand: "Medium", valueAdd: "High" },
      { name: "Xylitol Sweetener Precursor", industry: "Food Processing", demand: "Medium", valueAdd: "Very High" }
    ],
    storageGuidelines: "Store shredded cobs in dry bags; corn stalks in silage pits or dry bales.",
    transportGuidelines: "Jumbo bulk bags (500kg) or trailer trucks."
  },
  {
    id: "fruit-veg-waste",
    name: "Fruit & Vegetable Market Waste",
    group: "Fruit & Vegetable Waste",
    count: "7,800 Tons",
    listingsCount: 31,
    icon: "apple",
    description: "Citrus peels, vegetable stems, spoiled fruits for biogas, pectin extraction, and black soldier fly larvae feed.",
    image: "/images/waste/fruit-veg-waste.jpg",
    applications: [
      { name: "Bio-CNG & Electricity Generation", industry: "Municipal / Waste-to-Energy", demand: "Very High", valueAdd: "High" },
      { name: "BSFL (Black Soldier Fly) Protein Meal", industry: "Aqua & Poultry Feed", demand: "High", valueAdd: "Very High" },
      { name: "Citrus Essential Oils & Pectin", industry: "Flavors & Pharma", demand: "High", valueAdd: "Very High" },
      { name: "Enriched Vermicompost", industry: "Soil Health", demand: "High", valueAdd: "Medium" }
    ],
    storageGuidelines: "Cold storage or direct slurry tanks. Dispatch within 24-48 hours.",
    transportGuidelines: "Leachate-proof sealed tanker trucks or plastic crates."
  },
  {
    id: "animal-manure",
    name: "Cow Dung & Poultry Waste",
    group: "Animal / Organic Waste",
    count: "12,900 Tons",
    listingsCount: 44,
    icon: "milky-way",
    description: "Well-decomposed cow dung, poultry litter, and slurry for biogas, vermicompost, and organic manure.",
    image: "/images/waste/animal-manure.jpg",
    applications: [
      { name: "Compressed Bio-Gas (CBG)", industry: "Energy & City Gas", demand: "Very High", valueAdd: "High" },
      { name: "Premium Vermicompost Fertilizer", industry: "Agriculture & Landscaping", demand: "Very High", valueAdd: "High" },
      { name: "Cow Dung Pots & Eco-Logs", industry: "Nurseries & Green Cremation", demand: "High", valueAdd: "High" }
    ],
    storageGuidelines: "Covered aerobic compost yards or anaerobic digesters.",
    transportGuidelines: "Tipper trucks with bottom sealing or HDPE lined bags."
  },
  {
    id: "sawdust-wood",
    name: "Sawdust & Wood Residue",
    group: "Other Waste",
    count: "6,600 Tons",
    listingsCount: 28,
    icon: "axe",
    description: "Timber mill shavings, sawdust, and orchard pruning trimmings for pelletization and mushroom spawn.",
    image: "/images/waste/sawdust-wood.jpg",
    applications: [
      { name: "High-Grade Wood Pellets (ENplus)", industry: "Export & Heating", demand: "Very High", valueAdd: "High" },
      { name: "Shiitake / Oyster Mushroom Substrate", industry: "Mushroom Cultivation", demand: "High", valueAdd: "High" },
      { name: "Wood Plastic Composites (WPC)", industry: "Construction", demand: "Medium", valueAdd: "Very High" }
    ],
    storageGuidelines: "Dry covered storage; enforce strict fire safety protocols.",
    transportGuidelines: "Covered bulk trailers or 40kg PP bags."
  },
  {
    id: "rice-husk",
    name: "Rice Husk & Ash",
    group: "Other Waste",
    count: "9,200 Tons",
    listingsCount: 34,
    icon: "boxes",
    description: "Paddy mill husks and silica-rich Rice Husk Ash (RHA) for steel casting insulation and green cement.",
    image: "/images/waste/rice-husk.jpg",
    applications: [
      { name: "Rice Husk Ash (RHA) Silica", industry: "Green Concrete & Steel", demand: "High", valueAdd: "Very High" },
      { name: "Boiler Fluidized Bed Fuel", industry: "Process Steam", demand: "Very High", valueAdd: "Medium" },
      { name: "Silica Aerogels & Tyre Filler", industry: "Advanced Materials", demand: "Medium", valueAdd: "Very High" }
    ],
    storageGuidelines: "Sealed silos or dry warehouses to avoid wind dispersal.",
    transportGuidelines: "Pneumatic tanker trucks or high-capacity bulk carriers."
  }
];

// ==========================================
// 2. USERS: 20+ FARMERS & 15+ INDUSTRIAL BUYERS
// ==========================================
export const INITIAL_USERS = [
  // --- FARMERS (20+) ---
  {
    id: "usr-farmer-1",
    name: "Ramesh Patel",
    role: "farmer",
    roleLabel: "Farmer / Producer",
    avatar: "RP",
    email: "ramesh@greenfarmagro.in",
    phone: "+91 98765 43210",
    farmName: "GreenFarm Agro & Dairy",
    businessType: "Individual Progressive Farmer",
    gstin: "33AABCG1234F1Z8",
    farmSize: "32 Acres",
    primaryCrops: "Paddy, Coconut, Sugarcane",
    location: "Pollachi, Coimbatore, Tamil Nadu",
    district: "Coimbatore",
    state: "Tamil Nadu",
    pincode: "642001",
    lat: 10.6586,
    lng: 77.0084,
    verified: { phone: true, email: true, identity: true, gst: true },
    memberSince: "March 2024",
    totalEarnings: 284500,
    activeListingsCount: 4,
    completedSalesCount: 58,
    rating: 4.9,
    reviewsCount: 46
  },
  {
    id: "usr-farmer-2",
    name: "Sanjay Deshmukh",
    role: "farmer",
    roleLabel: "Farmer / Producer",
    avatar: "SD",
    email: "sanjay@kisanbiomass.org",
    phone: "+91 98450 11223",
    farmName: "Kisan Biomass Cooperative",
    businessType: "Farmer Producer Org (FPO)",
    gstin: "27AABCK9081E1Z4",
    farmSize: "120 Acres (FPO Collective)",
    primaryCrops: "Sugarcane, Soybean, Cotton",
    location: "Shiroli, Kolhapur, Maharashtra",
    district: "Kolhapur",
    state: "Maharashtra",
    pincode: "416003",
    lat: 16.705,
    lng: 74.2433,
    verified: { phone: true, email: true, identity: true, gst: true },
    memberSince: "January 2024",
    totalEarnings: 612000,
    activeListingsCount: 6,
    completedSalesCount: 114,
    rating: 4.9,
    reviewsCount: 89
  },
  {
    id: "usr-farmer-3",
    name: "Mathew Varghese",
    role: "farmer",
    roleLabel: "Farmer / Producer",
    avatar: "MV",
    email: "mathew@keralacoir.com",
    phone: "+91 97440 99887",
    farmName: "Kerala Coconut Growers Collective",
    businessType: "FPO / Agro-Estate",
    gstin: "32AABCM4567D1Z1",
    farmSize: "45 Acres",
    primaryCrops: "Coconut, Banana, Pepper",
    location: "Alappuzha, Kerala",
    district: "Alappuzha",
    state: "Kerala",
    pincode: "688001",
    lat: 9.4981,
    lng: 76.3388,
    verified: { phone: true, email: true, identity: true, gst: true },
    memberSince: "May 2024",
    totalEarnings: 345000,
    activeListingsCount: 3,
    completedSalesCount: 42,
    rating: 4.7,
    reviewsCount: 32
  },
  {
    id: "usr-farmer-4",
    name: "Gurpreet Singh",
    role: "farmer",
    roleLabel: "Farmer / Producer",
    avatar: "GS",
    email: "gurpreet@amritfarms.in",
    phone: "+91 98120 55443",
    farmName: "Amrit Dairy & Organic Farms",
    businessType: "Dairy & Grain Farm",
    gstin: "06AABCG7788P1Z9",
    farmSize: "60 Acres",
    primaryCrops: "Wheat, Paddy, Mustard",
    location: "Karnal, Haryana",
    district: "Karnal",
    state: "Haryana",
    pincode: "132001",
    lat: 29.6857,
    lng: 76.9905,
    verified: { phone: true, email: true, identity: true, gst: true },
    memberSince: "February 2024",
    totalEarnings: 520000,
    activeListingsCount: 5,
    completedSalesCount: 82,
    rating: 4.9,
    reviewsCount: 64
  },
  {
    id: "usr-farmer-5",
    name: "Harbhajan Gill",
    role: "farmer",
    roleLabel: "Farmer / Producer",
    avatar: "HG",
    email: "gill@punjabagro.com",
    phone: "+91 98720 33221",
    farmName: "Punjab Agro Green Solutions",
    businessType: "Modern Mechanized Farm",
    gstin: "03AABCH3344K1Z3",
    farmSize: "85 Acres",
    primaryCrops: "Paddy, Wheat, Potato",
    location: "Samrala, Ludhiana, Punjab",
    district: "Ludhiana",
    state: "Punjab",
    pincode: "141001",
    lat: 30.901,
    lng: 75.8573,
    verified: { phone: true, email: true, identity: true, gst: true },
    memberSince: "April 2024",
    totalEarnings: 680000,
    activeListingsCount: 4,
    completedSalesCount: 96,
    rating: 4.8,
    reviewsCount: 52
  },
  {
    id: "usr-farmer-6",
    name: "Bhavik Patel",
    role: "farmer",
    roleLabel: "Farmer / Producer",
    avatar: "BP",
    email: "bhavik@saurashtragro.in",
    phone: "+91 99250 88776",
    farmName: "Saurashtra Oil & Agro Mills",
    businessType: "Decorticating Unit & Farms",
    gstin: "24AABCS9988L1Z6",
    farmSize: "40 Acres",
    primaryCrops: "Groundnut, Cotton, Cumin",
    location: "Junagadh, Gujarat",
    district: "Junagadh",
    state: "Gujarat",
    pincode: "362001",
    lat: 21.5222,
    lng: 70.4579,
    verified: { phone: true, email: true, identity: true, gst: true },
    memberSince: "June 2024",
    totalEarnings: 310000,
    activeListingsCount: 3,
    completedSalesCount: 48,
    rating: 4.8,
    reviewsCount: 38
  },
  {
    id: "usr-farmer-7",
    name: "Murugan Selvam",
    role: "farmer",
    roleLabel: "Farmer / Producer",
    avatar: "MS",
    email: "murugan@thenivalley.com",
    phone: "+91 94430 77665",
    farmName: "Theni Valley Fruit Producers",
    businessType: "Horticulture Plantation",
    gstin: "33AABCM8899K1Z0",
    farmSize: "25 Acres",
    primaryCrops: "Banana, Grapes, Mango",
    location: "Cumbum, Theni, Tamil Nadu",
    district: "Theni",
    state: "Tamil Nadu",
    pincode: "625531",
    lat: 10.0104,
    lng: 77.4768,
    verified: { phone: true, email: true, identity: true, gst: true },
    memberSince: "July 2024",
    totalEarnings: 185000,
    activeListingsCount: 2,
    completedSalesCount: 29,
    rating: 4.6,
    reviewsCount: 19
  },
  {
    id: "usr-farmer-8",
    name: "Shivanna Gowda",
    role: "farmer",
    roleLabel: "Farmer / Producer",
    avatar: "SG",
    email: "shivanna@karnatakacorn.in",
    phone: "+91 94480 22334",
    farmName: "Karnataka Corn Producers Collective",
    businessType: "Farmer Cooperative",
    gstin: "29AABCK5544R1Z7",
    farmSize: "75 Acres",
    primaryCrops: "Maize, Arecanut, Sugarcane",
    location: "Davanagere, Karnataka",
    district: "Davanagere",
    state: "Karnataka",
    pincode: "577002",
    lat: 14.4644,
    lng: 75.9218,
    verified: { phone: true, email: true, identity: true, gst: true },
    memberSince: "March 2024",
    totalEarnings: 290000,
    activeListingsCount: 3,
    completedSalesCount: 41,
    rating: 4.8,
    reviewsCount: 29
  },
  {
    id: "usr-farmer-9",
    name: "Balwinder Brar",
    role: "farmer",
    roleLabel: "Farmer / Producer",
    avatar: "BB",
    email: "brar@bathindaagri.in",
    phone: "+91 98880 11992",
    farmName: "Malwa Agri Residue Enterprise",
    businessType: "Baling Contracting & Farming",
    gstin: "03AABCB1122A1Z8",
    farmSize: "150 Acres Managed",
    primaryCrops: "Paddy, Cotton, Wheat",
    location: "Bathinda, Punjab",
    district: "Bathinda",
    state: "Punjab",
    pincode: "151001",
    lat: 30.211,
    lng: 74.9455,
    verified: { phone: true, email: true, identity: true, gst: true },
    memberSince: "January 2024",
    totalEarnings: 820000,
    activeListingsCount: 5,
    completedSalesCount: 130,
    rating: 4.9,
    reviewsCount: 75
  },
  {
    id: "usr-farmer-10",
    name: "Chandrashekhar Reddy",
    role: "farmer",
    roleLabel: "Farmer / Producer",
    avatar: "CR",
    email: "reddy@telanganagri.org",
    phone: "+91 98490 88221",
    farmName: "Godavari Agro Biomass Hub",
    businessType: "Farmer Group",
    gstin: "36AABCC9900M1Z2",
    farmSize: "55 Acres",
    primaryCrops: "Cotton, Chilli, Paddy",
    location: "Warangal, Telangana",
    district: "Warangal",
    state: "Telangana",
    pincode: "506002",
    lat: 17.9689,
    lng: 79.5941,
    verified: { phone: true, email: true, identity: true, gst: true },
    memberSince: "April 2024",
    totalEarnings: 310000,
    activeListingsCount: 3,
    completedSalesCount: 38,
    rating: 4.7,
    reviewsCount: 28
  },
  {
    id: "usr-farmer-11",
    name: "Mukesh Yadav",
    role: "farmer",
    roleLabel: "Farmer / Producer",
    avatar: "MY",
    email: "mukesh@brajfarms.in",
    phone: "+91 94120 77334",
    farmName: "Brajbhumi Dairy & Organic Farm",
    businessType: "Dairy & Fodder Farm",
    gstin: "09AABCM6655P1Z1",
    farmSize: "35 Acres",
    primaryCrops: "Cow Dung, Mustard Straw, Wheat",
    location: "Mathura, Uttar Pradesh",
    district: "Mathura",
    state: "Uttar Pradesh",
    pincode: "281001",
    lat: 27.4924,
    lng: 77.6737,
    verified: { phone: true, email: true, identity: true, gst: true },
    memberSince: "May 2024",
    totalEarnings: 245000,
    activeListingsCount: 2,
    completedSalesCount: 34,
    rating: 4.7,
    reviewsCount: 22
  },
  {
    id: "usr-farmer-12",
    name: "Thirunavukkarasu K.",
    role: "farmer",
    roleLabel: "Farmer / Producer",
    avatar: "TK",
    email: "thiru@cauverydelta.in",
    phone: "+91 94440 12890",
    farmName: "Cauvery Delta Paddy Growers",
    businessType: "FPO Collective",
    gstin: "33AABCT4433D1Z9",
    farmSize: "110 Acres",
    primaryCrops: "Paddy, Black Gram, Banana",
    location: "Thanjavur, Tamil Nadu",
    district: "Thanjavur",
    state: "Tamil Nadu",
    pincode: "613001",
    lat: 10.787,
    lng: 79.1378,
    verified: { phone: true, email: true, identity: true, gst: true },
    memberSince: "February 2024",
    totalEarnings: 590000,
    activeListingsCount: 4,
    completedSalesCount: 78,
    rating: 4.8,
    reviewsCount: 54
  },
  {
    id: "usr-farmer-13",
    name: "Kishore Somani",
    role: "farmer",
    roleLabel: "Farmer / Producer",
    avatar: "KS",
    email: "kishore@indoreagri.in",
    phone: "+91 98260 55112",
    farmName: "Malwa Soya & Wheat Producers",
    businessType: "Individual Farmer",
    gstin: "23AABCK2211E1Z3",
    farmSize: "50 Acres",
    primaryCrops: "Soybean, Wheat, Garlic",
    location: "Indore, Madhya Pradesh",
    district: "Indore",
    state: "Madhya Pradesh",
    pincode: "452001",
    lat: 22.7196,
    lng: 75.8577,
    verified: { phone: true, email: true, identity: true, gst: true },
    memberSince: "June 2024",
    totalEarnings: 275000,
    activeListingsCount: 3,
    completedSalesCount: 36,
    rating: 4.8,
    reviewsCount: 26
  },
  {
    id: "usr-farmer-14",
    name: "Birendra Mahato",
    role: "farmer",
    roleLabel: "Farmer / Producer",
    avatar: "BM",
    email: "birendra@ranchifarms.in",
    phone: "+91 94310 99443",
    farmName: "Chota Nagpur Organic Agri FPO",
    businessType: "Tribal Farmer Cooperative",
    gstin: "20AABCM3322Q1Z5",
    farmSize: "90 Acres",
    primaryCrops: "Paddy, Vegetable Stems, Cow Dung",
    location: "Ranchi, Jharkhand",
    district: "Ranchi",
    state: "Jharkhand",
    pincode: "834001",
    lat: 23.3441,
    lng: 85.3096,
    verified: { phone: true, email: true, identity: true, gst: true },
    memberSince: "July 2024",
    totalEarnings: 160000,
    activeListingsCount: 2,
    completedSalesCount: 21,
    rating: 4.6,
    reviewsCount: 16
  },
  {
    id: "usr-farmer-15",
    name: "Apparao Naidu",
    role: "farmer",
    roleLabel: "Farmer / Producer",
    avatar: "AN",
    email: "apparao@andhrafarms.in",
    phone: "+91 98480 33881",
    farmName: "Godavari Rice & Sawmill Biomass",
    businessType: "Agro Enterprise",
    gstin: "37AABCA7766K1Z7",
    farmSize: "65 Acres",
    primaryCrops: "Paddy, Coconut, Rice Husk",
    location: "Rajahmundry, Andhra Pradesh",
    district: "East Godavari",
    state: "Andhra Pradesh",
    pincode: "533101",
    lat: 17.0005,
    lng: 81.804,
    verified: { phone: true, email: true, identity: true, gst: true },
    memberSince: "March 2024",
    totalEarnings: 430000,
    activeListingsCount: 4,
    completedSalesCount: 59,
    rating: 4.8,
    reviewsCount: 41
  },
  {
    id: "usr-farmer-16",
    name: "Devendra Patil",
    role: "farmer",
    roleLabel: "Farmer / Producer",
    avatar: "DP",
    email: "patil@nashikgrape.in",
    phone: "+91 98220 44556",
    farmName: "Sahyadri Agro Residues",
    businessType: "Orchard & Farm Residues",
    gstin: "27AABCD8899P1Z2",
    farmSize: "40 Acres",
    primaryCrops: "Grape Prunings, Sugarcane, Onion Stalks",
    location: "Niphad, Nashik, Maharashtra",
    district: "Nashik",
    state: "Maharashtra",
    pincode: "422303",
    lat: 20.0763,
    lng: 74.1105,
    verified: { phone: true, email: true, identity: true, gst: true },
    memberSince: "May 2024",
    totalEarnings: 215000,
    activeListingsCount: 3,
    completedSalesCount: 28,
    rating: 4.7,
    reviewsCount: 20
  },
  {
    id: "usr-farmer-17",
    name: "Jagdish Choudhary",
    role: "farmer",
    roleLabel: "Farmer / Producer",
    avatar: "JC",
    email: "jagdish@jaipuragri.in",
    phone: "+91 94140 66221",
    farmName: "Marwar Mustard & Cluster Bean Hub",
    businessType: "Farmer FPO",
    gstin: "08AABCJ1199N1Z4",
    farmSize: "80 Acres",
    primaryCrops: "Mustard Straw, Guar Stalks, Cow Dung",
    location: "Chomu, Jaipur, Rajasthan",
    district: "Jaipur",
    state: "Rajasthan",
    pincode: "303702",
    lat: 27.1724,
    lng: 75.722,
    verified: { phone: true, email: true, identity: true, gst: true },
    memberSince: "April 2024",
    totalEarnings: 330000,
    activeListingsCount: 3,
    completedSalesCount: 45,
    rating: 4.8,
    reviewsCount: 31
  },
  {
    id: "usr-farmer-18",
    name: "Kalyan Sundaram",
    role: "farmer",
    roleLabel: "Farmer / Producer",
    avatar: "KS",
    email: "kalyan@karnatakahusk.in",
    phone: "+91 94490 88332",
    farmName: "Coffee & Areca Growers Federation",
    businessType: "Planters Society",
    gstin: "29AABCK7788H1Z8",
    farmSize: "130 Acres (Federated)",
    primaryCrops: "Coffee Husk, Areca Nut Sheath, Sawdust",
    location: "Chikmagalur, Karnataka",
    district: "Chikmagalur",
    state: "Karnataka",
    pincode: "577101",
    lat: 13.3161,
    lng: 75.772,
    verified: { phone: true, email: true, identity: true, gst: true },
    memberSince: "February 2024",
    totalEarnings: 470000,
    activeListingsCount: 4,
    completedSalesCount: 62,
    rating: 4.9,
    reviewsCount: 45
  },
  {
    id: "usr-farmer-19",
    name: "Subhasis Roy",
    role: "farmer",
    roleLabel: "Farmer / Producer",
    avatar: "SR",
    email: "subhasis@bengalagro.in",
    phone: "+91 98300 77119",
    farmName: "Burdwan Golden Paddy Farmers",
    businessType: "Paddy Farmers Cooperative",
    gstin: "19AABCS6655L1Z1",
    farmSize: "100 Acres",
    primaryCrops: "Paddy Straw, Rice Husk, Jute Waste",
    location: "Bardhaman, West Bengal",
    district: "Purba Bardhaman",
    state: "West Bengal",
    pincode: "713101",
    lat: 23.2324,
    lng: 87.8615,
    verified: { phone: true, email: true, identity: true, gst: true },
    memberSince: "January 2024",
    totalEarnings: 540000,
    activeListingsCount: 4,
    completedSalesCount: 71,
    rating: 4.8,
    reviewsCount: 49
  },
  {
    id: "usr-farmer-20",
    name: "Pranab Gogoi",
    role: "farmer",
    roleLabel: "Farmer / Producer",
    avatar: "PG",
    email: "pranab@assambio.in",
    phone: "+91 94350 44228",
    farmName: "Brahmaputra Organic Growers",
    businessType: "Tea & Agri Waste Producer",
    gstin: "18AABCP9911K1Z6",
    farmSize: "60 Acres",
    primaryCrops: "Tea Waste, Paddy Straw, Sawdust",
    location: "Jorhat, Assam",
    district: "Jorhat",
    state: "Assam",
    pincode: "785001",
    lat: 26.7509,
    lng: 94.2037,
    verified: { phone: true, email: true, identity: true, gst: true },
    memberSince: "June 2024",
    totalEarnings: 195000,
    activeListingsCount: 2,
    completedSalesCount: 24,
    rating: 4.7,
    reviewsCount: 18
  },

  // --- BUYERS & RECYCLERS (15+) ---
  {
    id: "usr-buyer-1",
    name: "Rajesh Sharma",
    role: "buyer",
    roleLabel: "Buyer / Processor",
    avatar: "RS",
    email: "rajesh@agrofeedindustries.com",
    phone: "+91 98450 67890",
    companyName: "AgroFeed & Cattle Nutrition Ltd",
    industry: "Animal Feed & Silage",
    businessType: "Cattle Feed Manufacturer",
    gstin: "33AAACA9876C1Z4",
    requiredWasteTypes: ["paddy-straw", "wheat-straw", "maize-stalk-cob", "groundnut-shell"],
    monthlyRequirementTons: 150,
    location: "Coimbatore Industrial Zone, Tamil Nadu",
    district: "Coimbatore",
    state: "Tamil Nadu",
    pincode: "641018",
    lat: 11.0168,
    lng: 76.9558,
    verified: { phone: true, email: true, identity: true, gst: true },
    memberSince: "January 2024",
    totalPurchases: 785000,
    wastePurchasedTons: 68.5,
    rating: 4.9,
    reviewsCount: 42
  },
  {
    id: "usr-buyer-2",
    name: "Dr. Ananya Sen",
    role: "buyer",
    roleLabel: "Recycler / Biomass",
    avatar: "AS",
    email: "ananya@ecopellets.in",
    phone: "+91 99001 23456",
    companyName: "EcoPellets Clean Energy Tech",
    industry: "Biomass Briquetting & Power",
    businessType: "Renewable Energy Manufacturer",
    gstin: "29AABCE5678D1Z2",
    requiredWasteTypes: ["sugarcane-bagasse", "groundnut-shell", "cotton-stalk", "paddy-straw", "sawdust-wood"],
    monthlyRequirementTons: 350,
    location: "Peenya Industrial Area, Bengaluru, Karnataka",
    district: "Bengaluru Urban",
    state: "Karnataka",
    pincode: "560058",
    lat: 13.0285,
    lng: 77.5197,
    verified: { phone: true, email: true, identity: true, gst: true },
    memberSince: "November 2023",
    totalPurchases: 1850000,
    wastePurchasedTons: 240.0,
    rating: 5.0,
    reviewsCount: 68
  },
  {
    id: "usr-buyer-3",
    name: "Vikram Singhania",
    role: "buyer",
    roleLabel: "Buyer / Paper Mill",
    avatar: "VS",
    email: "vikram@pulpkraft.in",
    phone: "+91 98110 44332",
    companyName: "PulpKraft Eco Paper Mills",
    industry: "Paper & Packaging",
    businessType: "Tree-Free Paper Manufacturer",
    gstin: "06AAACP4411K1Z9",
    requiredWasteTypes: ["wheat-straw", "sugarcane-bagasse", "paddy-straw", "banana-waste"],
    monthlyRequirementTons: 280,
    location: "Sonipat, Haryana",
    district: "Sonipat",
    state: "Haryana",
    pincode: "131001",
    lat: 28.9931,
    lng: 77.0151,
    verified: { phone: true, email: true, identity: true, gst: true },
    memberSince: "February 2024",
    totalPurchases: 1420000,
    wastePurchasedTons: 190.0,
    rating: 4.8,
    reviewsCount: 38
  },
  {
    id: "usr-buyer-4",
    name: "Arunachalam Chettiar",
    role: "buyer",
    roleLabel: "Recycler / Activated Carbon",
    avatar: "AC",
    email: "arun@carbonbio.co.in",
    phone: "+91 94420 88991",
    companyName: "CarbonBio Filtration Technologies",
    industry: "Activated Carbon & Filters",
    businessType: "Carbon Export Enterprise",
    gstin: "33AABCC1122P1Z0",
    requiredWasteTypes: ["coconut-husk-shell", "rice-husk", "sawdust-wood"],
    monthlyRequirementTons: 200,
    location: "Tuticorin Port SEZ, Tamil Nadu",
    district: "Thoothukudi",
    state: "Tamil Nadu",
    pincode: "628001",
    lat: 8.7642,
    lng: 78.1348,
    verified: { phone: true, email: true, identity: true, gst: true },
    memberSince: "March 2024",
    totalPurchases: 960000,
    wastePurchasedTons: 110.0,
    rating: 4.9,
    reviewsCount: 31
  },
  {
    id: "usr-buyer-5",
    name: "Siddharth Mehta",
    role: "buyer",
    roleLabel: "Buyer / Biofuel",
    avatar: "SM",
    email: "siddharth@greencng.com",
    phone: "+91 98250 11993",
    companyName: "GreenCNG Bio-Gas Refineries",
    industry: "Bio-CNG & Biofuels",
    businessType: "SATAT Compressed BioGas Plant",
    gstin: "24AABCG5544J1Z6",
    requiredWasteTypes: ["animal-manure", "fruit-veg-waste", "sugarcane-bagasse", "paddy-straw"],
    monthlyRequirementTons: 500,
    location: "Sanand Industrial Estate, Ahmedabad, Gujarat",
    district: "Ahmedabad",
    state: "Gujarat",
    pincode: "382110",
    lat: 22.9868,
    lng: 72.3812,
    verified: { phone: true, email: true, identity: true, gst: true },
    memberSince: "December 2023",
    totalPurchases: 2400000,
    wastePurchasedTons: 420.0,
    rating: 4.9,
    reviewsCount: 84
  },
  {
    id: "usr-buyer-6",
    name: "Kavita Ramachandran",
    role: "buyer",
    roleLabel: "Buyer / Compost",
    avatar: "KR",
    email: "kavita@terraorganics.in",
    phone: "+91 98400 33221",
    companyName: "TerraPure Bio-Organics & Vermicompost",
    industry: "Organic Fertilizer & Vermiculture",
    businessType: "Certified Organic Fertilizer",
    gstin: "33AABCT9988D1Z5",
    requiredWasteTypes: ["animal-manure", "paddy-straw", "fruit-veg-waste", "coconut-husk-shell"],
    monthlyRequirementTons: 120,
    location: "Chengalpattu, Tamil Nadu",
    district: "Chengalpattu",
    state: "Tamil Nadu",
    pincode: "603001",
    lat: 12.6819,
    lng: 79.9888,
    verified: { phone: true, email: true, identity: true, gst: true },
    memberSince: "April 2024",
    totalPurchases: 540000,
    wastePurchasedTons: 75.0,
    rating: 4.8,
    reviewsCount: 29
  },
  {
    id: "usr-buyer-7",
    name: "Deepak Agarwal",
    role: "buyer",
    roleLabel: "Buyer / Eco Tableware",
    avatar: "DA",
    email: "deepak@chugreen.com",
    phone: "+91 98100 77665",
    companyName: "ChuGreen Compostable Packaging",
    industry: "Molded Fiber Packaging",
    businessType: "Eco Tableware Exporter",
    gstin: "07AAACD3344M1Z2",
    requiredWasteTypes: ["sugarcane-bagasse", "wheat-straw", "paddy-straw", "areca-waste"],
    monthlyRequirementTons: 180,
    location: "Noida Sector 80, Uttar Pradesh",
    district: "Gautam Buddha Nagar",
    state: "Uttar Pradesh",
    pincode: "201305",
    lat: 28.5355,
    lng: 77.391,
    verified: { phone: true, email: true, identity: true, gst: true },
    memberSince: "January 2024",
    totalPurchases: 1100000,
    wastePurchasedTons: 140.0,
    rating: 4.9,
    reviewsCount: 44
  },
  {
    id: "usr-buyer-8",
    name: "Gautam Nair",
    role: "buyer",
    roleLabel: "Buyer / Coir Exporter",
    avatar: "GN",
    email: "gautam@malabarcoir.com",
    phone: "+91 94470 55112",
    companyName: "Malabar Coir & Hydroponic Substrates",
    industry: "Hydroponics & Coir Geotextiles",
    businessType: "Export House",
    gstin: "32AAACG6677F1Z8",
    requiredWasteTypes: ["coconut-husk-shell"],
    monthlyRequirementTons: 250,
    location: "Kochi Port Export Zone, Kerala",
    district: "Ernakulam",
    state: "Kerala",
    pincode: "682003",
    lat: 9.9312,
    lng: 76.2673,
    verified: { phone: true, email: true, identity: true, gst: true },
    memberSince: "February 2024",
    totalPurchases: 1350000,
    wastePurchasedTons: 175.0,
    rating: 4.8,
    reviewsCount: 36
  },
  {
    id: "usr-buyer-9",
    name: "Sunil Jain",
    role: "buyer",
    roleLabel: "Buyer / Boiler Fuel",
    avatar: "SJ",
    email: "sunil@jaintextiles.in",
    phone: "+91 98290 44991",
    companyName: "Jain Textile & Dyeing Mills",
    industry: "Textile Processing & Steam",
    businessType: "Textile Conglomerate",
    gstin: "08AAACJ4455K1Z3",
    requiredWasteTypes: ["groundnut-shell", "cotton-stalk", "sawdust-wood", "sugarcane-bagasse"],
    monthlyRequirementTons: 300,
    location: "Bhilwara, Rajasthan",
    district: "Bhilwara",
    state: "Rajasthan",
    pincode: "311001",
    lat: 25.3463,
    lng: 74.6364,
    verified: { phone: true, email: true, identity: true, gst: true },
    memberSince: "March 2024",
    totalPurchases: 1600000,
    wastePurchasedTons: 210.0,
    rating: 4.7,
    reviewsCount: 40
  },
  {
    id: "usr-buyer-10",
    name: "Preeti Bhattacharya",
    role: "buyer",
    roleLabel: "Buyer / Mushroom Hub",
    avatar: "PB",
    email: "preeti@himalayanmushrooms.in",
    phone: "+91 94190 33887",
    companyName: "Himalayan Agro-Fungi & Spawn Lab",
    industry: "Mushroom Cultivation",
    businessType: "Commercial Mushroom Grower",
    gstin: "02AABCP7788L1Z9",
    requiredWasteTypes: ["wheat-straw", "paddy-straw", "sawdust-wood"],
    monthlyRequirementTons: 90,
    location: "Solan, Himachal Pradesh",
    district: "Solan",
    state: "Himachal Pradesh",
    pincode: "173212",
    lat: 30.9084,
    lng: 77.0999,
    verified: { phone: true, email: true, identity: true, gst: true },
    memberSince: "April 2024",
    totalPurchases: 420000,
    wastePurchasedTons: 52.0,
    rating: 4.8,
    reviewsCount: 25
  },
  {
    id: "usr-buyer-11",
    name: "Tushar Kothari",
    role: "buyer",
    roleLabel: "Buyer / Green Chemicals",
    avatar: "TK",
    email: "tushar@biochemcorp.in",
    phone: "+91 98200 66554",
    companyName: "BioChem Solvents & Furfural",
    industry: "Green Chemistry & Bio-Solvents",
    businessType: "Specialty Chemicals Manufacturer",
    gstin: "27AAACB2233M1Z1",
    requiredWasteTypes: ["groundnut-shell", "sugarcane-bagasse", "rice-husk"],
    monthlyRequirementTons: 220,
    location: "Tarapur MIDC, Palghar, Maharashtra",
    district: "Palghar",
    state: "Maharashtra",
    pincode: "401506",
    lat: 19.8347,
    lng: 72.6738,
    verified: { phone: true, email: true, identity: true, gst: true },
    memberSince: "May 2024",
    totalPurchases: 1150000,
    wastePurchasedTons: 135.0,
    rating: 4.9,
    reviewsCount: 33
  },
  {
    id: "usr-buyer-12",
    name: "Venkateswara Rao",
    role: "buyer",
    roleLabel: "Buyer / Cattle Feed",
    avatar: "VR",
    email: "rao@andhrafeed.com",
    phone: "+91 98481 22774",
    companyName: "Godavari Cattle & Aqua Feed Tech",
    industry: "Animal & Aqua Feed",
    businessType: "Feed Processing Unit",
    gstin: "37AAACG1122D1Z4",
    requiredWasteTypes: ["maize-stalk-cob", "paddy-straw", "groundnut-shell"],
    monthlyRequirementTons: 160,
    location: "Guntur, Andhra Pradesh",
    district: "Guntur",
    state: "Andhra Pradesh",
    pincode: "522002",
    lat: 16.3067,
    lng: 80.4365,
    verified: { phone: true, email: true, identity: true, gst: true },
    memberSince: "January 2024",
    totalPurchases: 890000,
    wastePurchasedTons: 105.0,
    rating: 4.8,
    reviewsCount: 30
  },
  {
    id: "usr-buyer-13",
    name: "Harish Chandra",
    role: "buyer",
    roleLabel: "Buyer / Eco Textiles",
    avatar: "HC",
    email: "harish@ananyafibers.in",
    phone: "+91 94432 99881",
    companyName: "Ananya Natural Agro-Fibers Ltd",
    industry: "Natural Textile Fibers",
    businessType: "Eco-Yarn Spinner",
    gstin: "33AAACA3344J1Z7",
    requiredWasteTypes: ["banana-waste", "cotton-stalk", "coconut-husk-shell"],
    monthlyRequirementTons: 80,
    location: "Tiruppur Textile Hub, Tamil Nadu",
    district: "Tiruppur",
    state: "Tamil Nadu",
    pincode: "641604",
    lat: 11.1085,
    lng: 77.3411,
    verified: { phone: true, email: true, identity: true, gst: true },
    memberSince: "March 2024",
    totalPurchases: 620000,
    wastePurchasedTons: 58.0,
    rating: 4.9,
    reviewsCount: 27
  },
  {
    id: "usr-buyer-14",
    name: "Ratan Tatawala",
    role: "buyer",
    roleLabel: "Buyer / Steel & Silica",
    avatar: "RT",
    email: "ratan@silicagreen.com",
    phone: "+91 98310 44992",
    companyName: "SilicaGreen Industrial Refractories",
    industry: "Steel Casting & Insulating Powders",
    businessType: "Refractory Material Plant",
    gstin: "19AAACS7788P1Z5",
    requiredWasteTypes: ["rice-husk", "sawdust-wood"],
    monthlyRequirementTons: 190,
    location: "Durgapur Industrial Complex, West Bengal",
    district: "Paschim Bardhaman",
    state: "West Bengal",
    pincode: "713201",
    lat: 23.5204,
    lng: 87.3119,
    verified: { phone: true, email: true, identity: true, gst: true },
    memberSince: "February 2024",
    totalPurchases: 1050000,
    wastePurchasedTons: 125.0,
    rating: 4.8,
    reviewsCount: 35
  },
  {
    id: "usr-buyer-15",
    name: "Manisha Goswami",
    role: "buyer",
    roleLabel: "Buyer / Waste-to-Energy",
    avatar: "MG",
    email: "manisha@urbangreenenergy.in",
    phone: "+91 98180 88229",
    companyName: "UrbanGreen City Biogas & Power",
    industry: "Municipal Organic Waste Power",
    businessType: "Waste to Energy Developer",
    gstin: "07AAACU9911K1Z2",
    requiredWasteTypes: ["fruit-veg-waste", "animal-manure", "paddy-straw"],
    monthlyRequirementTons: 400,
    location: "Okhla Industrial Area, New Delhi",
    district: "South Delhi",
    state: "Delhi",
    pincode: "110020",
    lat: 28.5355,
    lng: 77.2711,
    verified: { phone: true, email: true, identity: true, gst: true },
    memberSince: "December 2023",
    totalPurchases: 2100000,
    wastePurchasedTons: 350.0,
    rating: 4.9,
    reviewsCount: 57
  },

  // --- ADMIN (1) ---
  {
    id: "usr-admin-1",
    name: "Vikram Malhotra",
    role: "admin",
    roleLabel: "Platform Administrator",
    avatar: "VM",
    email: "admin@agriwaste.market",
    phone: "+91 90000 00001",
    companyName: "AgriWaste Central Exchange",
    businessType: "Platform Operations, Moderation & Governance",
    gstin: "07AAAAA0000A1Z5",
    location: "National Agri-Hub, New Delhi",
    district: "New Delhi",
    state: "Delhi",
    pincode: "110001",
    lat: 28.6139,
    lng: 77.209,
    verified: { phone: true, email: true, identity: true, gst: true },
    memberSince: "October 2023"
  }
];

// ==========================================
// 3. 50+ REALISTIC AGRI WASTE LISTINGS
// ==========================================
export const INITIAL_LISTINGS = [
  {
    id: "LST-1001",
    title: "Premium Dry Paddy Straw Bales (Round Machine Baled)",
    category: "paddy-straw",
    categoryName: "Paddy / Rice Straw",
    crop: "Paddy (Ponni Rice)",
    quantity: 12.5,
    unit: "Tons",
    price: 4200,
    priceUnit: "Per Ton",
    minOrderQty: 2.0,
    availableQty: 12.5,
    condition: "Dry",
    moisture: "11%",
    qualityGrade: "Grade A (Golden Dry)",
    packaging: "Machine Baled (25kg Bales)",
    harvestDate: "2026-08-14",
    expiryDate: "2027-02-14",
    pickupAvailability: "Immediate (Loading Machine Ready)",
    loadingAssistance: "Yes (Tractor loader provided on-site)",
    storageType: "Covered Shed Storage",
    location: "Pollachi, Tamil Nadu",
    district: "Coimbatore",
    state: "Tamil Nadu",
    pincode: "642001",
    distanceKm: 12,
    lat: 10.6586,
    lng: 77.0084,
    description: "High-quality sun-dried golden rice straw bales. Zero soil contamination, free of moisture or mold. Ideal for cattle dairy feed, bio-pellets, mushroom beds, and green packaging manufacturing.",
    images: [
      "/images/waste/paddy-straw.jpg"
    ],
    seller: {
      id: "usr-farmer-1",
      name: "Ramesh Patel",
      farmName: "GreenFarm Agro & Dairy",
      avatar: "RP",
      rating: 4.9,
      reviewsCount: 46,
      verified: true,
      phone: "+91 98765 43210"
    },
    status: "Approved",
    isApproved: true,
    views: 412,
    createdAt: "2026-08-15",
    featured: true
  },
  {
    id: "LST-1002",
    title: "Dense Crushed Sugarcane Bagasse (Boiler & Pellet Ready)",
    category: "sugarcane-bagasse",
    categoryName: "Sugarcane Bagasse",
    crop: "Sugarcane (Co 86032)",
    quantity: 25.0,
    unit: "Tons",
    price: 2100,
    priceUnit: "Per Ton",
    minOrderQty: 5.0,
    availableQty: 25.0,
    condition: "Dry",
    moisture: "16%",
    qualityGrade: "Grade A (Mill Crushed)",
    packaging: "Loose Bulk Tipper Load",
    harvestDate: "2026-08-12",
    expiryDate: "2026-12-12",
    pickupAvailability: "Available Now",
    loadingAssistance: "Yes (Excavator on-site)",
    storageType: "Covered Bunker Shed",
    location: "Shiroli, Kolhapur, Maharashtra",
    district: "Kolhapur",
    state: "Maharashtra",
    pincode: "416003",
    distanceKm: 28,
    lat: 16.705,
    lng: 74.2433,
    description: "Clean mill-crushed sugarcane bagasse with uniform fiber length. Exceptional calorific output (~4100 kcal/kg bone dry basis) for industrial power boilers, tableware thermoforming, and bio-coal briquettes.",
    images: [
      "/images/waste/sugarcane-bagasse.jpg"
    ],
    seller: {
      id: "usr-farmer-2",
      name: "Sanjay Deshmukh",
      farmName: "Kisan Biomass Cooperative",
      avatar: "SD",
      rating: 4.9,
      reviewsCount: 89,
      verified: true,
      phone: "+91 98450 11223"
    },
    status: "Approved",
    isApproved: true,
    views: 650,
    createdAt: "2026-08-11",
    featured: true
  },
  {
    id: "LST-1003",
    title: "Matured Coconut Shells & Seasoned Coir Husk",
    category: "coconut-husk-shell",
    categoryName: "Coconut Husk & Shells",
    crop: "Coconut (West Coast Tall)",
    quantity: 8.0,
    unit: "Tons",
    price: 6800,
    priceUnit: "Per Ton",
    minOrderQty: 1.0,
    availableQty: 8.0,
    condition: "Dry",
    moisture: "8%",
    qualityGrade: "Premium Export Grade",
    packaging: "Gunny Bags (50kg each)",
    harvestDate: "2026-08-08",
    expiryDate: "2027-08-08",
    pickupAvailability: "Available Now",
    loadingAssistance: "Yes (Labour team provided)",
    storageType: "Concrete Floor Shed",
    location: "Alappuzha, Kerala",
    district: "Alappuzha",
    state: "Kerala",
    pincode: "688001",
    distanceKm: 45,
    lat: 9.4981,
    lng: 76.3388,
    description: "Hard sun-cured coconut shells with high fixed carbon (>72%) and low ash content. Best feedstock for activated carbon purification filters, high-grade barbecue briquettes, and decorative craft articles.",
    images: [
      "/images/waste/coconut-husk-shell.jpg"
    ],
    seller: {
      id: "usr-farmer-3",
      name: "Mathew Varghese",
      farmName: "Kerala Coconut Growers",
      avatar: "MV",
      rating: 4.7,
      reviewsCount: 32,
      verified: true,
      phone: "+91 97440 99887"
    },
    status: "Approved",
    isApproved: true,
    views: 480,
    createdAt: "2026-08-09",
    featured: true
  },
  {
    id: "LST-1004",
    title: "Aged Organic Cow Dung Manure (NPK Enriched & Screened)",
    category: "animal-manure",
    categoryName: "Cow Dung & Poultry Waste",
    crop: "Dairy Cattle Slurry & Dung",
    quantity: 30.0,
    unit: "Tons",
    price: 1750,
    priceUnit: "Per Ton",
    minOrderQty: 3.0,
    availableQty: 30.0,
    condition: "Processed",
    moisture: "22%",
    qualityGrade: "Grade A (90-Day Aerobic Aged)",
    packaging: "Bulk Tipper / HDPE Bags (40kg)",
    harvestDate: "2026-08-16",
    expiryDate: "2027-04-16",
    pickupAvailability: "Available Now",
    loadingAssistance: "Yes (Backhoe Loader on farm)",
    storageType: "Covered Concrete Composting Pit",
    location: "Karnal, Haryana",
    district: "Karnal",
    state: "Haryana",
    pincode: "132001",
    distanceKm: 18,
    lat: 29.6857,
    lng: 76.9905,
    description: "Fully matured 90-day aged organic cow manure enriched with beneficial trichoderma and mycorrhiza. Completely weed-seed free, excellent for horticultural orchards, organic vegetable polyhouses, and terrace soil conditioning.",
    images: [
      "/images/waste/animal-manure.jpg"
    ],
    seller: {
      id: "usr-farmer-4",
      name: "Gurpreet Singh",
      farmName: "Amrit Dairy & Organic Farms",
      avatar: "GS",
      rating: 4.9,
      reviewsCount: 64,
      verified: true,
      phone: "+91 98120 55443"
    },
    status: "Approved",
    isApproved: true,
    views: 590,
    createdAt: "2026-08-13",
    featured: true
  },
  {
    id: "LST-1005",
    title: "Fine Shredded Wheat Straw (Cattle Fodder & Tree-Free Pulp)",
    category: "wheat-straw",
    categoryName: "Wheat Straw",
    crop: "Wheat (HD 2967)",
    quantity: 18.0,
    unit: "Tons",
    price: 5100,
    priceUnit: "Per Ton",
    minOrderQty: 2.0,
    availableQty: 18.0,
    condition: "Dry",
    moisture: "9%",
    qualityGrade: "Grade A (Turi / Bhusa)",
    packaging: "Square Compressed Bales (30kg)",
    harvestDate: "2026-08-04",
    expiryDate: "2027-03-04",
    pickupAvailability: "Available Now",
    loadingAssistance: "Yes",
    storageType: "Enclosed Warehouse Shed",
    location: "Samrala, Ludhiana, Punjab",
    district: "Ludhiana",
    state: "Punjab",
    pincode: "141001",
    distanceKm: 35,
    lat: 30.901,
    lng: 75.8573,
    description: "Dust-extracted golden wheat turi/straw with soft fiber texture. Free from mud or foreign particles. Widely demanded by commercial dairy cow farms and paper mills producing eco-friendly corrugated craft paper.",
    images: [
      "/images/waste/wheat-straw.jpg"
    ],
    seller: {
      id: "usr-farmer-5",
      name: "Harbhajan Gill",
      farmName: "Punjab Agro Green Solutions",
      avatar: "HG",
      rating: 4.8,
      reviewsCount: 52,
      verified: true,
      phone: "+91 98720 33221"
    },
    status: "Approved",
    isApproved: true,
    views: 420,
    createdAt: "2026-08-07",
    featured: false
  },
  {
    id: "LST-1006",
    title: "Crushed Groundnut Shells / White-Coal Briquette Feedstock",
    category: "groundnut-shell",
    categoryName: "Groundnut Shells / Husks",
    crop: "Groundnut (GG 20)",
    quantity: 14.0,
    unit: "Tons",
    price: 3300,
    priceUnit: "Per Ton",
    minOrderQty: 2.0,
    availableQty: 14.0,
    condition: "Dry",
    moisture: "8%",
    qualityGrade: "Clean Decorticated",
    packaging: "Loose Bulk / Jumbo Bags",
    harvestDate: "2026-08-10",
    expiryDate: "2027-02-10",
    pickupAvailability: "Available Now",
    loadingAssistance: "Yes (Belt Conveyor)",
    storageType: "Dry Grain Elevator Shed",
    location: "Junagadh, Gujarat",
    district: "Junagadh",
    state: "Gujarat",
    pincode: "362001",
    distanceKm: 22,
    lat: 21.5222,
    lng: 70.4579,
    description: "Dry and clean peanut shells separated during commercial decortication. Uniform moisture content, high gross calorific value (approx 4250 kcal/kg), ideal for pellet mills, boiler heating, and furfural chemical synthesis.",
    images: [
      "/images/waste/groundnut-shell.jpg"
    ],
    seller: {
      id: "usr-farmer-6",
      name: "Bhavik Patel",
      farmName: "Saurashtra Oil & Agro Mills",
      avatar: "BP",
      rating: 4.8,
      reviewsCount: 38,
      verified: true,
      phone: "+91 99250 88776"
    },
    status: "Approved",
    isApproved: true,
    views: 310,
    createdAt: "2026-08-10",
    featured: false
  },
  {
    id: "LST-1007",
    title: "Fresh Banana Pseudo-Stem Fiber & Enriched Sap",
    category: "banana-waste",
    categoryName: "Banana Pseudo-Stem & Leaves",
    crop: "Grand Naine Banana",
    quantity: 6.0,
    unit: "Tons",
    price: 3600,
    priceUnit: "Per Ton",
    minOrderQty: 1.0,
    availableQty: 6.0,
    condition: "Fresh",
    moisture: "38%",
    qualityGrade: "Grade A Fresh Cut",
    packaging: "Bundles / Crates",
    harvestDate: "2026-08-17",
    expiryDate: "2026-08-25",
    pickupAvailability: "Immediate (Fresh Harvest)",
    loadingAssistance: "Yes",
    storageType: "Shaded Orchard Yard",
    location: "Cumbum, Theni, Tamil Nadu",
    district: "Theni",
    state: "Tamil Nadu",
    pincode: "625531",
    distanceKm: 52,
    lat: 10.0104,
    lng: 77.4768,
    description: "Freshly harvested banana stems rich in natural cellulosic fibers. Raw material for eco-textile spinning, handmade artisanal paper, organic liquid sap fertilizer, and vermiculture bed base.",
    images: [
      "/images/waste/banana-waste.jpg"
    ],
    seller: {
      id: "usr-farmer-7",
      name: "Murugan Selvam",
      farmName: "Theni Valley Fruit Producers",
      avatar: "MS",
      rating: 4.6,
      reviewsCount: 19,
      verified: true,
      phone: "+91 94430 77665"
    },
    status: "Approved",
    isApproved: true,
    views: 240,
    createdAt: "2026-08-14",
    featured: false
  },
  {
    id: "LST-1008",
    title: "Chopped Corn Stover & De-kerneled Cobs",
    category: "maize-stalk-cob",
    categoryName: "Maize Stalks & Cobs",
    crop: "Maize (Hybrid Corn)",
    quantity: 11.0,
    unit: "Tons",
    price: 2800,
    priceUnit: "Per Ton",
    minOrderQty: 2.0,
    availableQty: 11.0,
    condition: "Dry",
    moisture: "13%",
    qualityGrade: "Grade A Chopped",
    packaging: "Jumbo PP Bags (500kg)",
    harvestDate: "2026-08-08",
    expiryDate: "2027-01-08",
    pickupAvailability: "Available Now",
    loadingAssistance: "Yes",
    storageType: "Dry Grain Shed",
    location: "Davanagere, Karnataka",
    district: "Davanagere",
    state: "Karnataka",
    pincode: "577002",
    lat: 14.4644,
    lng: 75.9218,
    description: "Mechanically chopped corn stalks and dry cobs. High fiber content, ideal for animal silage formulation, bio-coal briquettes, and industrial absorbent material for spill remediation.",
    images: [
      "/images/waste/maize-stalk-cob.jpg"
    ],
    seller: {
      id: "usr-farmer-8",
      name: "Shivanna Gowda",
      farmName: "Karnataka Corn Producers",
      avatar: "SG",
      rating: 4.8,
      reviewsCount: 29,
      verified: true,
      phone: "+91 94480 22334"
    },
    status: "Approved",
    isApproved: true,
    views: 320,
    createdAt: "2026-08-09",
    featured: false
  },
  {
    id: "LST-1009",
    title: "Cotton Stalks for Biomass Briquettes & Particle Boards",
    category: "cotton-stalk",
    categoryName: "Cotton Stalks & Waste",
    crop: "Bt Cotton Stalks",
    quantity: 16.0,
    unit: "Tons",
    price: 2400,
    priceUnit: "Per Ton",
    minOrderQty: 3.0,
    availableQty: 16.0,
    condition: "Dry",
    moisture: "12%",
    qualityGrade: "Grade B (Field Bundled)",
    packaging: "Bundled Stems / Flatbed",
    harvestDate: "2026-08-06",
    expiryDate: "2027-02-06",
    pickupAvailability: "Available Now",
    loadingAssistance: "Yes",
    storageType: "Open Yard Covered with Tarpaulin",
    location: "Bathinda, Punjab",
    district: "Bathinda",
    state: "Punjab",
    pincode: "151001",
    lat: 30.211,
    lng: 74.9455,
    description: "Woody cotton plant stalks harvested after boll plucking. Sturdy high-lignin biomass suited for heavy industrial gasifiers, pressed particle boards, and bio-char preparation.",
    images: [
      "/images/waste/cotton-stalk.jpg"
    ],
    seller: {
      id: "usr-farmer-9",
      name: "Balwinder Brar",
      farmName: "Malwa Agri Residue",
      avatar: "BB",
      rating: 4.9,
      reviewsCount: 75,
      verified: true,
      phone: "+91 98880 11992"
    },
    status: "Approved",
    isApproved: true,
    views: 390,
    createdAt: "2026-08-08",
    featured: false
  },
  {
    id: "LST-1010",
    title: "Organic Vegetable Market Scrap & Fruit Pulp Slurry",
    category: "fruit-veg-waste",
    categoryName: "Fruit & Vegetable Market Waste",
    crop: "Vegetable Stems, Citrus Peels, Spoiled Veg",
    quantity: 8.5,
    unit: "Tons",
    price: 950,
    priceUnit: "Per Ton",
    minOrderQty: 2.0,
    availableQty: 8.5,
    condition: "Fresh / Slurry",
    moisture: "75%",
    qualityGrade: "Grade A Organic Feedstock",
    packaging: "Sealed Tanker / Crates",
    harvestDate: "2026-08-18",
    expiryDate: "2026-08-21",
    pickupAvailability: "Immediate 24-hr Pickup",
    loadingAssistance: "Yes",
    storageType: "Direct Slurry Sump",
    location: "Warangal, Telangana",
    district: "Warangal",
    state: "Telangana",
    pincode: "506002",
    lat: 17.9689,
    lng: 79.5941,
    description: "Daily fresh organic sorted vegetable and fruit pulp scrap from wholesale APMC market. High biomethane potential (~0.45 m3/kg VS) for commercial Bio-CNG plants and insect BSFL larvae rearing.",
    images: [
      "/images/waste/fruit-veg-waste.jpg"
    ],
    seller: {
      id: "usr-farmer-10",
      name: "Chandrashekhar Reddy",
      farmName: "Godavari Agro Biomass",
      avatar: "CR",
      rating: 4.7,
      reviewsCount: 28,
      verified: true,
      phone: "+91 98490 88221"
    },
    status: "Approved",
    isApproved: true,
    views: 295,
    createdAt: "2026-08-16",
    featured: false
  },
  {
    id: "LST-1011",
    title: "Pure Pine & Teak Sawdust Shavings (Low Ash, Kiln Dry)",
    category: "sawdust-wood",
    categoryName: "Sawdust & Wood Residue",
    crop: "Timber Mill Residue",
    quantity: 15.0,
    unit: "Tons",
    price: 3800,
    priceUnit: "Per Ton",
    minOrderQty: 2.0,
    availableQty: 15.0,
    condition: "Dry",
    moisture: "7%",
    qualityGrade: "Grade A Screened",
    packaging: "PP Woven Sacks (40kg)",
    harvestDate: "2026-08-14",
    expiryDate: "2027-08-14",
    pickupAvailability: "Available Now",
    loadingAssistance: "Yes",
    storageType: "Covered Dry Godown",
    location: "Chikmagalur, Karnataka",
    district: "Chikmagalur",
    state: "Karnataka",
    pincode: "577101",
    lat: 13.3161,
    lng: 75.772,
    description: "Uniformly sieved timber sawmill sawdust with ultra-low ash content (<0.5%). Top raw material for export-spec wood pellets, oyster mushroom substrate bags, and wood-plastic composite boards.",
    images: [
      "/images/waste/sawdust-wood.jpg"
    ],
    seller: {
      id: "usr-farmer-18",
      name: "Kalyan Sundaram",
      farmName: "Coffee & Areca Growers",
      avatar: "KS",
      rating: 4.9,
      reviewsCount: 45,
      verified: true,
      phone: "+91 94490 88332"
    },
    status: "Approved",
    isApproved: true,
    views: 375,
    createdAt: "2026-08-15",
    featured: true
  },
  {
    id: "LST-1012",
    title: "Raw Paddy Rice Husk (Clean Golden Mill Residue)",
    category: "rice-husk",
    categoryName: "Rice Husk & Ash",
    crop: "Paddy Milling Husk",
    quantity: 20.0,
    unit: "Tons",
    price: 2600,
    priceUnit: "Per Ton",
    minOrderQty: 4.0,
    availableQty: 20.0,
    condition: "Dry",
    moisture: "9%",
    qualityGrade: "Grade A Mill Cleaned",
    packaging: "Loose Tipper / Bags",
    harvestDate: "2026-08-11",
    expiryDate: "2027-08-11",
    pickupAvailability: "Available Now",
    loadingAssistance: "Yes",
    storageType: "Steel Storage Silo",
    location: "Bardhaman, West Bengal",
    district: "Purba Bardhaman",
    state: "West Bengal",
    pincode: "713101",
    lat: 23.2324,
    lng: 87.8615,
    description: "Direct mill paddy husk free from unhusked grain. Excellent boiler fuel, silica extraction feedstock, and poultry house bedding with high thermal insulation.",
    images: [
      "/images/waste/rice-husk.jpg"
    ],
    seller: {
      id: "usr-farmer-19",
      name: "Subhasis Roy",
      farmName: "Burdwan Golden Paddy",
      avatar: "SR",
      rating: 4.8,
      reviewsCount: 49,
      verified: true,
      phone: "+91 98300 77119"
    },
    status: "Approved",
    isApproved: true,
    views: 460,
    createdAt: "2026-08-12",
    featured: false
  },
  {
    id: "LST-1013",
    title: "Raw Coffee Parchment Husk & Cherry Pulp Waste",
    category: "rice-husk",
    categoryName: "Rice Husk & Ash",
    crop: "Arabica & Robusta Coffee",
    quantity: 7.0,
    unit: "Tons",
    price: 3200,
    priceUnit: "Per Ton",
    minOrderQty: 1.0,
    availableQty: 7.0,
    condition: "Dry",
    moisture: "10%",
    qualityGrade: "Grade A",
    packaging: "Gunny Bags (50kg)",
    harvestDate: "2026-08-05",
    expiryDate: "2027-02-05",
    pickupAvailability: "Available Now",
    loadingAssistance: "Yes",
    storageType: "Dry Warehouse",
    location: "Chikmagalur, Karnataka",
    district: "Chikmagalur",
    state: "Karnataka",
    pincode: "577101",
    lat: 13.3161,
    lng: 75.772,
    description: "Cured coffee husk rich in potassium and organic polyphenols. Premium organic compost enhancer and bio-fuel pellet component.",
    images: [
      "/images/waste/rice-husk.jpg"
    ],
    seller: {
      id: "usr-farmer-18",
      name: "Kalyan Sundaram",
      farmName: "Coffee & Areca Growers",
      avatar: "KS",
      rating: 4.9,
      reviewsCount: 45,
      verified: true,
      phone: "+91 94490 88332"
    },
    status: "Approved",
    isApproved: true,
    views: 190,
    createdAt: "2026-08-06",
    featured: false
  },
  {
    id: "LST-1014",
    title: "Poultry Litter Manure (Nitrogen-Rich Dry Droppings)",
    category: "animal-manure",
    categoryName: "Cow Dung & Poultry Waste",
    crop: "Broiler & Layer Bird Manure",
    quantity: 18.0,
    unit: "Tons",
    price: 1950,
    priceUnit: "Per Ton",
    minOrderQty: 3.0,
    availableQty: 18.0,
    condition: "Semi-Dry",
    moisture: "24%",
    qualityGrade: "Commercial Grade (High N)",
    packaging: "HDPE Bags (50kg)",
    harvestDate: "2026-08-15",
    expiryDate: "2027-02-15",
    pickupAvailability: "Available Now",
    loadingAssistance: "Yes",
    storageType: "Covered Shed",
    location: "Namakkal, Tamil Nadu",
    district: "Namakkal",
    state: "Tamil Nadu",
    pincode: "637001",
    lat: 11.2189,
    lng: 78.1674,
    description: "High nitrogen-phosphorus dry poultry manure from commercial poultry sheds. Ideal for horticultural crops, sugarcane basal dressing, and enriched bio-fertilizer formulation.",
    images: [
      "/images/waste/animal-manure.jpg"
    ],
    seller: {
      id: "usr-farmer-1",
      name: "Ramesh Patel",
      farmName: "GreenFarm Agro & Dairy",
      avatar: "RP",
      rating: 4.9,
      reviewsCount: 46,
      verified: true,
      phone: "+91 98765 43210"
    },
    status: "Approved",
    isApproved: true,
    views: 310,
    createdAt: "2026-08-15",
    featured: false
  },
  {
    id: "LST-1015",
    title: "Areca Nut Sheaths / Biodegradable Plate Raw Material",
    category: "coconut-husk-shell",
    categoryName: "Coconut Husk & Shells",
    crop: "Arecanut Palm Sheaths",
    quantity: 3.5,
    unit: "Tons",
    price: 8500,
    priceUnit: "Per Ton",
    minOrderQty: 0.5,
    availableQty: 3.5,
    condition: "Dry",
    moisture: "10%",
    qualityGrade: "Grade A (Clean & Flat)",
    packaging: "Bundles of 100 Sheaths",
    harvestDate: "2026-08-12",
    expiryDate: "2027-08-12",
    pickupAvailability: "Immediate Pickup",
    loadingAssistance: "Yes",
    storageType: "Enclosed Warehouse",
    location: "Shimoga, Karnataka",
    district: "Shimoga",
    state: "Karnataka",
    pincode: "577201",
    lat: 13.9299,
    lng: 75.5681,
    description: "Naturally shed dry arecanut leaf sheaths. Washed and flattened, ready for heat-press molding into disposable eco-plates, bowls, and packaging containers.",
    images: [
      "/images/waste/coconut-husk-shell.jpg"
    ],
    seller: {
      id: "usr-farmer-8",
      name: "Shivanna Gowda",
      farmName: "Karnataka Corn & Areca",
      avatar: "SG",
      rating: 4.8,
      reviewsCount: 29,
      verified: true,
      phone: "+91 94480 22334"
    },
    status: "Approved",
    isApproved: true,
    views: 280,
    createdAt: "2026-08-13",
    featured: false
  }
];

// Dynamically generate additional listings to ensure 50+ diverse listings across all states
const ADDITIONAL_LISTINGS_DATA = [
  { crop: "Paddy Straw Bales", cat: "paddy-straw", price: 4400, unit: "Tons", qty: 15, state: "Punjab", district: "Patiala", lat: 30.3398, lng: 76.3869, farmer: 5 },
  { crop: "Sugarcane Bagasse Loose", cat: "sugarcane-bagasse", price: 2300, unit: "Tons", qty: 30, state: "Uttar Pradesh", district: "Muzaffarnagar", lat: 29.4727, lng: 77.7085, farmer: 11 },
  { crop: "Wheat Straw Bhusa", cat: "wheat-straw", price: 5300, unit: "Tons", qty: 12, state: "Madhya Pradesh", district: "Indore", lat: 22.7196, lng: 75.8577, farmer: 13 },
  { crop: "Coir Pith Blocks 5kg", cat: "coconut-husk-shell", price: 7200, unit: "Tons", qty: 10, state: "Tamil Nadu", district: "Coimbatore", lat: 11.0168, lng: 76.9558, farmer: 1 },
  { crop: "Cotton Residue Chipped", cat: "cotton-stalk", price: 2500, unit: "Tons", qty: 22, state: "Gujarat", district: "Rajkot", lat: 22.3039, lng: 70.8022, farmer: 6 },
  { crop: "Groundnut Shell Briquette Feed", cat: "groundnut-shell", price: 3500, unit: "Tons", qty: 16, state: "Andhra Pradesh", district: "Anantapur", lat: 14.6819, lng: 77.6006, farmer: 15 },
  { crop: "Banana Pseudo Stem Trimmings", cat: "banana-waste", price: 3700, unit: "Tons", qty: 5, state: "Maharashtra", district: "Jalgaon", lat: 21.0077, lng: 75.5626, farmer: 16 },
  { crop: "Maize Cob Grit Clean", cat: "maize-stalk-cob", price: 2950, unit: "Tons", qty: 14, state: "Telangana", district: "Nizamabad", lat: 18.6725, lng: 78.0941, farmer: 10 },
  { crop: "Bio-CNG Organic Vegetable Slurry", cat: "fruit-veg-waste", price: 1100, unit: "Tons", qty: 9, state: "Delhi", district: "South Delhi", lat: 28.5355, lng: 77.2711, farmer: 4 },
  { crop: "Enriched Vermicompost Dung", cat: "animal-manure", price: 2100, unit: "Tons", qty: 25, state: "Rajasthan", district: "Jaipur", lat: 26.9124, lng: 75.7873, farmer: 17 },
  { crop: "Pine Wood Sawdust Bags", cat: "sawdust-wood", price: 3900, unit: "Tons", qty: 12, state: "Himachal Pradesh", district: "Solan", lat: 30.9084, lng: 77.0999, farmer: 4 },
  { crop: "Rice Husk Ash High Silica", cat: "rice-husk", price: 4200, unit: "Tons", qty: 18, state: "West Bengal", district: "Purba Bardhaman", lat: 23.2324, lng: 87.8615, farmer: 19 },
  { crop: "Mustard Straw Bundles", cat: "cotton-stalk", price: 2200, unit: "Tons", qty: 20, state: "Rajasthan", district: "Bharatpur", lat: 27.2152, lng: 77.503, farmer: 17 },
  { crop: "Paddy Straw Bales Super Dry", cat: "paddy-straw", price: 4350, unit: "Tons", qty: 16, state: "Punjab", district: "Amritsar", lat: 31.634, lng: 74.8723, farmer: 9 },
  { crop: "Sugarcane Bagasse High Fiber", cat: "sugarcane-bagasse", price: 2150, unit: "Tons", qty: 40, state: "Maharashtra", district: "Pune", lat: 18.5204, lng: 73.8567, farmer: 2 },
  { crop: "Wheat Straw Clean Bales", cat: "wheat-straw", price: 5250, unit: "Tons", qty: 15, state: "Haryana", district: "Kurukshetra", lat: 29.9695, lng: 76.8783, farmer: 4 },
  { crop: "Coconut Charcoal Shells", cat: "coconut-husk-shell", price: 7100, unit: "Tons", qty: 7, state: "Kerala", district: "Kozhikode", lat: 11.2588, lng: 75.7804, farmer: 3 },
  { crop: "Tea Pruning Biomass", cat: "sawdust-wood", price: 3100, unit: "Tons", qty: 10, state: "Assam", district: "Jorhat", lat: 26.7509, lng: 94.2037, farmer: 20 },
  { crop: "Paddy Husk Boiler Grade", cat: "rice-husk", price: 2700, unit: "Tons", qty: 25, state: "Andhra Pradesh", district: "West Godavari", lat: 16.7107, lng: 81.0952, farmer: 15 },
  { crop: "Dairy Cow Dung Slurry", cat: "animal-manure", price: 1650, unit: "Tons", qty: 35, state: "Uttar Pradesh", district: "Mathura", lat: 27.4924, lng: 77.6737, farmer: 11 },
  { crop: "Soya Stover Straw", cat: "cotton-stalk", price: 2600, unit: "Tons", qty: 14, state: "Madhya Pradesh", district: "Ujjain", lat: 23.1765, lng: 75.7885, farmer: 13 },
  { crop: "Paddy Straw Bales Export Standard", cat: "paddy-straw", price: 4600, unit: "Tons", qty: 10, state: "Tamil Nadu", district: "Thanjavur", lat: 10.787, lng: 79.1378, farmer: 12 },
  { crop: "Sugarcane Bagasse Baled", cat: "sugarcane-bagasse", price: 2400, unit: "Tons", qty: 20, state: "Karnataka", district: "Belagavi", lat: 15.8497, lng: 74.4977, farmer: 8 },
  { crop: "Wheat Bhusa Cattle Fodder", cat: "wheat-straw", price: 5150, unit: "Tons", qty: 22, state: "Punjab", district: "Jalandhar", lat: 31.326, lng: 75.5762, farmer: 5 },
  { crop: "Coir Geotextile Fiber", cat: "coconut-husk-shell", price: 8200, unit: "Tons", qty: 6, state: "Tamil Nadu", district: "Pollachi", lat: 10.6586, lng: 77.0084, farmer: 1 },
  { crop: "Cotton Stalk Pellets Feed", cat: "cotton-stalk", price: 2750, unit: "Tons", qty: 18, state: "Gujarat", district: "Surat", lat: 21.1702, lng: 72.8311, farmer: 6 },
  { crop: "Banana Fiber Rolls", cat: "banana-waste", price: 4100, unit: "Tons", qty: 4, state: "Kerala", district: "Thrissur", lat: 10.5276, lng: 76.2144, farmer: 3 },
  { crop: "Corn Silage Fermented", cat: "maize-stalk-cob", price: 3200, unit: "Tons", qty: 12, state: "Karnataka", district: "Hassan", lat: 13.0033, lng: 76.1004, farmer: 8 },
  { crop: "Grapevine Pruning Mulch", cat: "sawdust-wood", price: 2800, unit: "Tons", qty: 8, state: "Maharashtra", district: "Nashik", lat: 20.0763, lng: 74.1105, farmer: 16 },
  { crop: "Citrus Peel Solid Scrap", cat: "fruit-veg-waste", price: 1250, unit: "Tons", qty: 11, state: "Maharashtra", district: "Nagpur", lat: 21.1458, lng: 79.0882, farmer: 2 },
  { crop: "Paddy Straw Bales Local", cat: "paddy-straw", price: 4100, unit: "Tons", qty: 14, state: "Haryana", district: "Fatehabad", lat: 29.5147, lng: 75.4542, farmer: 4 },
  { crop: "Guar Stalk Biomass", cat: "cotton-stalk", price: 2400, unit: "Tons", qty: 15, state: "Rajasthan", district: "Bikaner", lat: 28.0229, lng: 73.3119, farmer: 17 },
  { crop: "Coffee Pulp Manure Mix", cat: "animal-manure", price: 2250, unit: "Tons", qty: 16, state: "Karnataka", district: "Kodagu", lat: 12.3375, lng: 75.8069, farmer: 18 },
  { crop: "Wheat Straw Chopped", cat: "wheat-straw", price: 5000, unit: "Tons", qty: 20, state: "Uttar Pradesh", district: "Meerut", lat: 28.9845, lng: 77.7064, farmer: 11 },
  { crop: "Rice Husk Bulk Tipper", cat: "rice-husk", price: 2550, unit: "Tons", qty: 30, state: "West Bengal", district: "Hooghly", lat: 22.8963, lng: 88.2461, farmer: 19 },
  { crop: "Organic Farm Manure Bulk", cat: "animal-manure", price: 1800, unit: "Tons", qty: 28, state: "Jharkhand", district: "Ranchi", lat: 23.3441, lng: 85.3096, farmer: 14 }
];

ADDITIONAL_LISTINGS_DATA.forEach((item, index) => {
  const listingId = `LST-${1016 + index}`;
  const farmerUser = INITIAL_USERS.find(u => u.id === `usr-farmer-${item.farmer}`) || INITIAL_USERS[0];
  const catObj = INITIAL_CATEGORIES.find(c => c.id === item.cat) || INITIAL_CATEGORIES[0];

  INITIAL_LISTINGS.push({
    id: listingId,
    title: `${item.crop} (${item.state})`,
    category: item.cat,
    categoryName: catObj.name,
    crop: item.crop,
    quantity: item.qty,
    unit: item.unit,
    price: item.price,
    priceUnit: `Per ${item.unit.slice(0, -1)}`,
    minOrderQty: Math.max(1, Math.round(item.qty * 0.15)),
    availableQty: item.qty,
    condition: "Dry",
    moisture: "12%",
    qualityGrade: "Grade A",
    packaging: "Standard Packing",
    harvestDate: "2026-08-10",
    expiryDate: "2027-02-10",
    pickupAvailability: "Available Now",
    loadingAssistance: "Yes",
    storageType: "Covered Warehouse Shed",
    location: `${item.district}, ${item.state}`,
    district: item.district,
    state: item.state,
    pincode: "110001",
    distanceKm: 20 + (index * 7) % 65,
    lat: item.lat,
    lng: item.lng,
    description: `High-grade ${item.crop.toLowerCase()} sourced from verified farms in ${item.district}, ${item.state}. Well preserved, strictly checked for optimal moisture and contamination-free handling.`,
    images: [
      catObj.image
    ],
    seller: {
      id: farmerUser.id,
      name: farmerUser.name,
      farmName: farmerUser.farmName || farmerUser.name,
      avatar: farmerUser.avatar,
      rating: farmerUser.rating || 4.8,
      reviewsCount: farmerUser.reviewsCount || 25,
      verified: true,
      phone: farmerUser.phone
    },
    status: index === 33 ? "Pending Approval" : index === 34 ? "Sold" : "Approved",
    isApproved: index !== 33,
    views: 120 + index * 18,
    createdAt: `2026-08-${String(1 + (index % 16)).padStart(2, "0")}`,
    featured: index % 6 === 0
  });
});

// ==========================================
// 4. 30+ REALISTIC ORDERS WITH TIMELINES
// ==========================================
export const INITIAL_ORDERS = [
  {
    id: "AGW-10245",
    listingId: "LST-1001",
    listingTitle: "Premium Dry Paddy Straw Bales",
    category: "paddy-straw",
    quantity: 5.0,
    unit: "Tons",
    unitPrice: 4200,
    subtotal: 21000,
    transportationFee: 2400,
    platformFee: 420,
    taxGst: 1050,
    totalAmount: 24870,
    status: "In Transit",
    statusStep: 6, // 1: Placed, 2: Payment Confirmed, 3: Accepted, 4: Pickup Scheduled, 5: Collected, 6: In Transit, 7: Delivered, 8: Completed
    paymentStatus: "Paid (UPI)",
    paymentMethod: "UPI (Google Pay)",
    transactionId: "TXN-UPI-9847291038",
    createdAt: "2026-08-16 10:30 AM",
    pickupDate: "2026-08-17 09:00 AM",
    estimatedDelivery: "2026-08-18 04:30 PM",
    seller: {
      id: "usr-farmer-1",
      name: "Ramesh Patel",
      farmName: "GreenFarm Agro & Dairy",
      phone: "+91 98765 43210",
      pickupAddress: "Farm Gate #3, Anaimalai Road, Pollachi, TN - 642001"
    },
    buyer: {
      id: "usr-buyer-1",
      name: "Rajesh Sharma",
      company: "AgroFeed & Cattle Nutrition Ltd",
      phone: "+91 98450 67890",
      deliveryAddress: "Plot 42, SIDCO Industrial Estate, Kurichi, Coimbatore, TN - 641021"
    },
    logistics: {
      carrier: "AgriLogistics Express",
      driverName: "Murugesan K.",
      driverPhone: "+91 98421 88776",
      vehicleNumber: "TN-38-AX-4821 (Eicher Pro 6-Tonner)",
      currentLocation: "Kinathukadavu Toll Plaza (18 km from destination)",
      lat: 10.8236,
      lng: 77.0185
    },
    timeline: [
      { step: "Order Placed", time: "16 Aug, 10:30 AM", completed: true },
      { step: "Payment Confirmed", time: "16 Aug, 10:32 AM", completed: true },
      { step: "Seller Accepted", time: "16 Aug, 11:15 AM", completed: true },
      { step: "Pickup Scheduled", time: "17 Aug, 08:30 AM", completed: true },
      { step: "Waste Collected", time: "17 Aug, 09:15 AM", completed: true },
      { step: "In Transit", time: "17 Aug, 11:00 AM", completed: true, active: true },
      { step: "Delivered", time: "Est. 18 Aug, 04:30 PM", completed: false },
      { step: "Completed", time: "Pending confirmation", completed: false }
    ]
  },
  {
    id: "AGW-10246",
    listingId: "LST-1002",
    listingTitle: "Dense Crushed Sugarcane Bagasse",
    category: "sugarcane-bagasse",
    quantity: 15.0,
    unit: "Tons",
    unitPrice: 2100,
    subtotal: 31500,
    transportationFee: 4200,
    platformFee: 630,
    taxGst: 1575,
    totalAmount: 37905,
    status: "Pickup Scheduled",
    statusStep: 4,
    paymentStatus: "Paid (Net Banking)",
    paymentMethod: "HDFC Net Banking",
    transactionId: "TXN-NB-7788443322",
    createdAt: "2026-08-16 02:45 PM",
    pickupDate: "2026-08-18 10:00 AM",
    estimatedDelivery: "2026-08-19 06:00 PM",
    seller: {
      id: "usr-farmer-2",
      name: "Sanjay Deshmukh",
      farmName: "Kisan Biomass Cooperative",
      phone: "+91 98450 11223",
      pickupAddress: "Sugar Mill Compound, Shiroli MIDC, Kolhapur, MH - 416003"
    },
    buyer: {
      id: "usr-buyer-2",
      name: "Dr. Ananya Sen",
      company: "EcoPellets Clean Energy Tech",
      phone: "+91 99001 23456",
      deliveryAddress: "Pellet Plant #4, Peenya Stage II, Bengaluru, KA - 560058"
    },
    logistics: {
      carrier: "Kisan Freight Network",
      driverName: "Subhash Patil",
      driverPhone: "+91 97654 32190",
      vehicleNumber: "MH-09-CV-9022 (Tata LPT 1613 16-Ton)",
      currentLocation: "Yard Loading Dock, Kolhapur",
      lat: 16.705,
      lng: 74.2433
    },
    timeline: [
      { step: "Order Placed", time: "16 Aug, 02:45 PM", completed: true },
      { step: "Payment Confirmed", time: "16 Aug, 02:50 PM", completed: true },
      { step: "Seller Accepted", time: "16 Aug, 04:00 PM", completed: true },
      { step: "Pickup Scheduled", time: "17 Aug, 10:00 AM", completed: true, active: true },
      { step: "Waste Collected", time: "Est. 18 Aug, 10:00 AM", completed: false },
      { step: "In Transit", time: "Est. 18 Aug, 01:00 PM", completed: false },
      { step: "Delivered", time: "Est. 19 Aug, 06:00 PM", completed: false },
      { step: "Completed", time: "Pending confirmation", completed: false }
    ]
  },
  {
    id: "AGW-10247",
    listingId: "LST-1004",
    listingTitle: "Aged Organic Cow Dung Manure",
    category: "animal-manure",
    quantity: 10.0,
    unit: "Tons",
    unitPrice: 1750,
    subtotal: 17500,
    transportationFee: 2200,
    platformFee: 350,
    taxGst: 875,
    totalAmount: 20925,
    status: "Completed",
    statusStep: 8,
    paymentStatus: "Completed",
    paymentMethod: "AgroPay Wallet",
    transactionId: "TXN-WAL-11223344",
    createdAt: "2026-08-10 09:15 AM",
    pickupDate: "2026-08-11 08:00 AM",
    estimatedDelivery: "2026-08-11 03:00 PM",
    seller: {
      id: "usr-farmer-4",
      name: "Gurpreet Singh",
      farmName: "Amrit Dairy & Organic Farms",
      phone: "+91 98120 55443",
      pickupAddress: "GT Road, Karnal, Haryana - 132001"
    },
    buyer: {
      id: "usr-buyer-6",
      name: "Kavita Ramachandran",
      company: "TerraPure Bio-Organics",
      phone: "+91 98400 33221",
      deliveryAddress: "Agro Processing Unit, Panipat Hub, Haryana"
    },
    logistics: {
      carrier: "Haryana Green Transporters",
      driverName: "Baldev Kumar",
      driverPhone: "+91 98112 33445",
      vehicleNumber: "HR-05-BG-7711",
      currentLocation: "Delivered at Destination",
      lat: 29.6857,
      lng: 76.9905
    },
    timeline: [
      { step: "Order Placed", time: "10 Aug, 09:15 AM", completed: true },
      { step: "Payment Confirmed", time: "10 Aug, 09:20 AM", completed: true },
      { step: "Seller Accepted", time: "10 Aug, 10:30 AM", completed: true },
      { step: "Pickup Scheduled", time: "11 Aug, 07:00 AM", completed: true },
      { step: "Waste Collected", time: "11 Aug, 08:00 AM", completed: true },
      { step: "In Transit", time: "11 Aug, 10:30 AM", completed: true },
      { step: "Delivered", time: "11 Aug, 02:45 PM", completed: true },
      { step: "Completed", time: "11 Aug, 03:00 PM", completed: true, active: true }
    ]
  }
];

// Generate orders 10248 to 10275 to fulfill 30+ orders requirement across various statuses
const STATUSES = ["Order Placed", "Payment Confirmed", "Seller Accepted", "Pickup Scheduled", "Waste Collected", "In Transit", "Delivered", "Completed", "Cancelled"];
for (let i = 4; i <= 32; i++) {
  const orderId = `AGW-${10244 + i}`;
  const listing = INITIAL_LISTINGS[i % INITIAL_LISTINGS.length];
  const buyer = INITIAL_USERS.find(u => u.role === "buyer" && u.id === `usr-buyer-${(i % 15) + 1}`) || INITIAL_USERS[20];
  const farmer = INITIAL_USERS.find(u => u.id === listing.seller.id) || INITIAL_USERS[0];
  const qty = Math.max(2, (i * 1.5) % 15);
  const subtotal = Math.round(qty * listing.price);
  const transFee = Math.round(1500 + (i * 180) % 3000);
  const platFee = Math.round(subtotal * 0.02);
  const tax = Math.round(subtotal * 0.05);
  const total = subtotal + transFee + platFee + tax;
  const status = STATUSES[i % STATUSES.length];
  const stepIdx = STATUSES.indexOf(status) + 1;

  INITIAL_ORDERS.push({
    id: orderId,
    listingId: listing.id,
    listingTitle: listing.title,
    category: listing.category,
    quantity: qty,
    unit: listing.unit,
    unitPrice: listing.price,
    subtotal: subtotal,
    transportationFee: transFee,
    platformFee: platFee,
    taxGst: tax,
    totalAmount: total,
    status: status,
    statusStep: stepIdx,
    paymentStatus: status === "Order Placed" ? "Pending" : status === "Cancelled" ? "Refunded" : "Paid",
    paymentMethod: i % 3 === 0 ? "UPI (PhonePe)" : i % 3 === 1 ? "HDFC Net Banking" : "Corporate Card",
    transactionId: `TXN-${orderId}-9988`,
    createdAt: `2026-08-${String(Math.max(1, 18 - Math.floor(i / 2))).padStart(2, "0")} 11:00 AM`,
    pickupDate: `2026-08-${String(Math.max(2, 19 - Math.floor(i / 2))).padStart(2, "0")} 09:00 AM`,
    estimatedDelivery: `2026-08-${String(Math.max(3, 20 - Math.floor(i / 2))).padStart(2, "0")} 05:00 PM`,
    seller: {
      id: farmer.id,
      name: farmer.name,
      farmName: farmer.farmName,
      phone: farmer.phone,
      pickupAddress: farmer.location
    },
    buyer: {
      id: buyer.id,
      name: buyer.name,
      company: buyer.companyName || buyer.name,
      phone: buyer.phone,
      deliveryAddress: buyer.location
    },
    logistics: {
      carrier: "National AgriFreight Line",
      driverName: "Ram Chander",
      driverPhone: "+91 98440 22331",
      vehicleNumber: `DL-01-AG-${4000 + i}`,
      currentLocation: status === "In Transit" ? "En route on National Highway" : status === "Delivered" ? "Delivered at warehouse" : "Scheduled for pickup",
      lat: farmer.lat || 28.6139,
      lng: farmer.lng || 77.209
    },
    timeline: [
      { step: "Order Placed", time: "Day 1, 10:00 AM", completed: stepIdx >= 1 },
      { step: "Payment Confirmed", time: "Day 1, 10:10 AM", completed: stepIdx >= 2 },
      { step: "Seller Accepted", time: "Day 1, 11:30 AM", completed: stepIdx >= 3 },
      { step: "Pickup Scheduled", time: "Day 2, 09:00 AM", completed: stepIdx >= 4 },
      { step: "Waste Collected", time: "Day 2, 10:00 AM", completed: stepIdx >= 5 },
      { step: "In Transit", time: "Day 2, 01:00 PM", completed: stepIdx >= 6 },
      { step: "Delivered", time: "Day 3, 04:00 PM", completed: stepIdx >= 7 },
      { step: "Completed", time: "Day 3, 05:00 PM", completed: stepIdx >= 8 }
    ]
  });
}

// ==========================================
// 5. 30+ REVIEWS & RATINGS
// ==========================================
export const INITIAL_REVIEWS = [
  {
    id: "REV-101",
    orderId: "AGW-10247",
    sellerId: "usr-farmer-4",
    sellerName: "Gurpreet Singh (Amrit Dairy)",
    buyerId: "usr-buyer-6",
    buyerName: "Kavita Ramachandran (TerraPure Bio-Organics)",
    overallRating: 5,
    qualityRating: 5,
    communicationRating: 5,
    deliveryRating: 5,
    date: "12 August 2026",
    comment: "Excellent quality aged cow manure with minimal moisture and zero weed seeds. Transporter arrived strictly on time with weighbridge slip. Will definitely order recurring truckloads!",
    wasteType: "Cow Dung Manure",
    helpfulCount: 14
  },
  {
    id: "REV-102",
    orderId: "AGW-10245",
    sellerId: "usr-farmer-1",
    sellerName: "Ramesh Patel (GreenFarm Agro)",
    buyerId: "usr-buyer-1",
    buyerName: "Rajesh Sharma (AgroFeed Ltd)",
    overallRating: 5,
    qualityRating: 5,
    communicationRating: 5,
    deliveryRating: 4,
    date: "08 August 2026",
    comment: "Top notch round baled rice straw. Clean golden yellow color, moisture verified under 12% on our lab meter. Smooth loading support at the farm gate.",
    wasteType: "Paddy Straw Bales",
    helpfulCount: 22
  },
  {
    id: "REV-103",
    orderId: "AGW-10246",
    sellerId: "usr-farmer-2",
    sellerName: "Sanjay Deshmukh (Kisan Biomass)",
    buyerId: "usr-buyer-2",
    buyerName: "Dr. Ananya Sen (EcoPellets Tech)",
    overallRating: 5,
    qualityRating: 5,
    communicationRating: 5,
    deliveryRating: 5,
    date: "04 August 2026",
    comment: "Bagasse fiber was dry and clean, calorific value exceeded 4150 kcal/kg. Super fast dispatch and transparent weighing process. Great partner for biomass boiler fuel!",
    wasteType: "Sugarcane Bagasse",
    helpfulCount: 19
  }
];

// Generate reviews 104 to 132 for 30+ reviews total
for (let i = 4; i <= 32; i++) {
  const farmer = INITIAL_USERS[i % 20];
  const buyer = INITIAL_USERS[20 + (i % 15)];
  const cat = INITIAL_CATEGORIES[i % INITIAL_CATEGORIES.length];
  const ratings = [5, 5, 4, 5, 4, 5, 5, 4];
  const ratingVal = ratings[i % ratings.length];

  INITIAL_REVIEWS.push({
    id: `REV-${100 + i}`,
    orderId: `AGW-${10244 + i}`,
    sellerId: farmer.id,
    sellerName: `${farmer.name} (${farmer.farmName})`,
    buyerId: buyer.id,
    buyerName: `${buyer.name} (${buyer.companyName || buyer.name})`,
    overallRating: ratingVal,
    qualityRating: ratingVal,
    communicationRating: 5,
    deliveryRating: ratingVal === 5 ? 5 : 4,
    date: `${Math.max(1, 18 - Math.floor(i / 2))} August 2026`,
    comment: `Reliable supply of ${cat.name}. Packaging was sturdy and verified moisture complied with listed specifications. Farmer was very cooperative during truck weighing.`,
    wasteType: cat.name,
    helpfulCount: (i * 3) % 15
  });
}

// ==========================================
// 6. COMPLAINTS & DISPUTES
// ==========================================
export const INITIAL_COMPLAINTS = [
  {
    id: "CMP-401",
    orderId: "AGW-10248",
    userId: "usr-buyer-1",
    userName: "Rajesh Sharma",
    userRole: "buyer",
    targetUserId: "usr-farmer-6",
    targetUserName: "Bhavik Patel",
    complaintType: "Quality Mismatch",
    description: "Moisture content in delivered groundnut shell batch was 18% instead of the specified 8%. Requesting partial adjustment.",
    attachment: "lab_moisture_report.pdf",
    status: "Under Review", // Open, Under Review, Resolved, Closed
    adminResponse: "Admin reviewing lab report with seller. Contacted transporter for weighbridge transit log.",
    createdAt: "2026-08-16",
    resolvedDate: null
  },
  {
    id: "CMP-402",
    orderId: "AGW-10249",
    userId: "usr-farmer-5",
    userName: "Harbhajan Gill",
    userRole: "farmer",
    targetUserId: "usr-buyer-3",
    targetUserName: "Vikram Singhania",
    complaintType: "Delayed Pickup",
    description: "Buyer truck delayed by 36 hours beyond scheduled appointment. Shed storage space occupied.",
    attachment: "shed_storage_gatepass.jpg",
    status: "Resolved",
    adminResponse: "Buyer rescheduled dedicated container truck with expedited detention waiver compensation credited to farmer wallet.",
    createdAt: "2026-08-12",
    resolvedDate: "2026-08-14"
  }
];

// ==========================================
// 7. CONVERSATIONS (CHAT)
// ==========================================
export const INITIAL_CONVERSATIONS = [
  {
    id: "conv-1",
    otherUserId: "usr-buyer-1",
    otherUserName: "Rajesh Sharma",
    otherUserRole: "Buyer (AgroFeed Ltd)",
    otherUserAvatar: "RS",
    listingId: "LST-1001",
    listingTitle: "Rice Straw (12.5 Tons)",
    lastMessage: "Yes, 12.5 tons are baled with 11% moisture and ready for pickup.",
    lastTimestamp: "10:45 AM",
    unreadCount: 1,
    online: true,
    messages: [
      { id: "msg-101", senderId: "usr-buyer-1", senderName: "Rajesh Sharma", text: "Namaste Ramesh ji, is the 12.5 ton rice straw lot available for immediate dispatch?", timestamp: "10:30 AM", isSender: false },
      { id: "msg-102", senderId: "usr-farmer-1", senderName: "Ramesh Patel", text: "Namaste Rajesh ji! Yes, all 12.5 tons are round machine baled at 11% moisture in our elevated shed.", timestamp: "10:35 AM", isSender: true },
      { id: "msg-103", senderId: "usr-buyer-1", senderName: "Rajesh Sharma", text: "Great! Can we schedule our 10-wheel tipper truck for pickup tomorrow morning at 8:30 AM?", timestamp: "10:40 AM", isSender: false },
      { id: "msg-104", senderId: "usr-farmer-1", senderName: "Ramesh Patel", text: "Yes, our front-end tractor loader team will be on-site ready to assist loading.", timestamp: "10:45 AM", isSender: true }
    ]
  },
  {
    id: "conv-2",
    otherUserId: "usr-buyer-2",
    otherUserName: "Dr. Ananya Sen",
    otherUserRole: "Recycler (EcoPellets Tech)",
    otherUserAvatar: "AS",
    listingId: "LST-1002",
    listingTitle: "Sugarcane Bagasse (25 Tons)",
    lastMessage: "Our transporter will arrive tomorrow with weighbridge verification.",
    lastTimestamp: "Yesterday",
    unreadCount: 0,
    online: true,
    messages: [
      { id: "msg-201", senderId: "usr-buyer-2", senderName: "Dr. Ananya Sen", text: "Hello Sanjay ji, we placed order #AGW-10246 for 15 tons of crushed bagasse.", timestamp: "Yesterday, 04:15 PM", isSender: false },
      { id: "msg-202", senderId: "usr-farmer-2", senderName: "Sanjay Deshmukh", text: "Received with thanks! We have cordoned the batch at our Shiroli MIDC yard.", timestamp: "Yesterday, 04:30 PM", isSender: true },
      { id: "msg-203", senderId: "usr-buyer-2", senderName: "Dr. Ananya Sen", text: "Our transporter will arrive tomorrow with weighbridge verification.", timestamp: "Yesterday, 05:00 PM", isSender: false }
    ]
  }
];

// ==========================================
// 8. NOTIFICATIONS
// ==========================================
export const INITIAL_NOTIFICATIONS = [
  {
    id: "notif-1",
    type: "order",
    title: "New Purchase Order Received",
    message: "AgroFeed Ltd placed Order #AGW-10245 for 5.0 Tons Paddy Straw (₹24,870).",
    time: "15 minutes ago",
    unread: true,
    icon: "shopping-bag",
    link: "#orders"
  },
  {
    id: "notif-2",
    type: "transit",
    title: "Order #AGW-10245 In Transit",
    message: "Driver Murugesan K. is 18 km away from the destination toll plaza.",
    time: "1 hour ago",
    unread: true,
    icon: "truck",
    link: "#orders"
  },
  {
    id: "notif-3",
    type: "listing",
    title: "Listing Verified & Approved",
    message: "Your listing 'Premium Dry Paddy Straw Bales' has been published to the national marketplace.",
    time: "Yesterday",
    unread: false,
    icon: "check-circle",
    link: "#marketplace"
  },
  {
    id: "notif-4",
    type: "payment",
    title: "Escrow Payment Received — ₹37,905",
    message: "Payment for Sugarcane Bagasse Order #AGW-10246 successfully secured in escrow.",
    time: "2 days ago",
    unread: false,
    icon: "credit-card",
    link: "#farmer-dashboard"
  },
  {
    id: "notif-5",
    type: "ai",
    title: "Smart AI Buyer Match",
    message: "4 industrial biomass plants near Coimbatore are seeking paddy straw at ₹4,200+/Ton.",
    time: "3 days ago",
    unread: false,
    icon: "sparkles",
    link: "#marketplace"
  }
];

// ==========================================
// 9. SUSTAINABILITY & IMPACT METRICS
// ==========================================
export const SUSTAINABILITY_METRICS = {
  totalWasteReusedTons: 28450,
  co2EmissionsAvoidedTons: 19800,
  farmersBenefited: 12400,
  businessesConnected: 6850,
  stubBurnIncidentsAvoided: 2940,
  treesEquivalentSaved: 580000,
  carbonCreditsGenerated: 19800,
  totalFarmerIncomeGeneratedINR: 78500000
};
